### ISSUE TITLE
Mancata lettura file transazioni della release 2.0.0-rc1

### ISSUE THREAD

**Issue by mmelega-icteam** [pagopa/rtd-ms-transaction-filter#101]
Di seguito la configurazione ed esito della esecuzione (allegate alla issue)

- application.yml
- enviroment-bpd-ms-rtd-ms-transaction-filter: setting variabili di ambiente
- CSTAR.03111.TRNLOG.20210101.120000.666.CSV: file di test delle transazioni sottomesso al BA 2.0.0-rc1
- batch_job_execution.xlsx e batch_step_execution.xlsx: contenuto tabelle di batch per l'esecuzione del file di transazione
- log del processo (generato con l'opzione root: DEBUG)

il comportamento osservato è il seguente:

- il file delle transazioni scompare dalla folder di input configurata /muvi/IN
- le due fasi del batch si concludono senza errori
- nella folder di output configurata /muvi/OUT non è presente nessun file (eventualmente vuoto)
- in nessun log compare il nome del file in input delle transazioni
- in batch_step_execution non c'è evidenza nei contatori della lettura delle righe del file delle transazioni.

Come nota aggiuntiva la nuova configurazione application.yml è stata ottenuta partendo da quella attualmente in produzione ed integrando le sezioni mancanti della nuova configurazione di esempio presente sul GitLab

Grazie

[Mancata lettura file transazioni della release 2.0.0-rc1.zip](https://github.com/pagopa/rtd-ms-transaction-filter/files/6703198/Mancata.lettura.file.transazioni.della.release.2.0.0-rc1.zip)

**Comment by alessio-cialini-sia** [comment]
Ciao, attualmente nello zip allegato manca il log di esecuzione. Mi servirebbe per determinare la causa della mancata elaborazione.

Grazie

**Comment by mmelega-icteam** [comment]
Sto provando caricarlo ma è piuttosto grande e github non lo accetta. C'è
un altro modo con cui mandarlo?

MM

On Wed, Jun 23, 2021 at 7:08 PM alessio-cialini-sia <
***@***.***> wrote:

> Ciao, attualmente nello zip allegato manca il log di esecuzione. Mi
> servirebbe per determinare la causa della mancata elaborazione.
>
> Grazie
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F101%23issuecomment-867012285&e=4cb69f4a&h=e955a6bc&f=n&p=y>,
> or unsubscribe
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARR2G63IZUEVH7KQYNTAHC3TUIIG3ANCNFSM47GCA4CQ&e=4cb69f4a&h=05286d12&f=n&p=y>
> .[image: Web Bug from
> https://github.com/notifications/beacon/ARR2G6Z2U2W4ZOEEKGT5K7DTUIIG3A5CNFSM47GCA4C2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOGOWY5PI.gif]
>


-- 

*Massimiliano Melega*
Senior Business Intelligence Engineer & Solution Architect
***@***.***
+39 035 4232 287

[image: ICTeam Logo] <http://www.icteam.it>
* <http://www.icteam.it> *

*ICTeam S.p.A. • Via Azzano San Paolo, 139 Grassobbio BG 24050 Italy *P.IVA
02691680165 – Bergamo - REA-BG-314847

-- 
*
*
*Il contenuto di questo messaggio e-mail e di ogni eventuale allegato è 
strettamente confidenziale e indirizzato esclusivamente al destinatario 
indicato. Tutte le informazioni contenute sono soggette ad obbligo di 
riservatezza ai sensi del Regolamento UE 2016/679 GDPR e del D.Lgs 196/2003 
e sm. Il trattamento non autorizzato del contenuto trasmesso e/o allegato 
dal mittente è vietato. In caso di erronea ricezione il destinatario è 
pregato di contattare immediatamente il mittente e cancellare al più presto 
il messaggio. Grazie.    *

**Comment by alessio-cialini-sia** [comment]
Ciao, invialo tramite mail, il mio indirizzo è presente nelle ultime comunicazioni sul tema. 

Grazie

**Comment by alessio-cialini-sia** [comment]
Riuscite a fornirci il log per mail? vale anche inviare a TeamCentroStella@sia.eu... altra cosa che chiedo è l'estrazione per l'estrazione del campo short_context (il campo nel db che contiene il filename)

Grazie

**Comment by alessio-cialini-sia** [comment]
Chiederei inoltre di fornire il sistema operativo utilizzato per il test, per facilitare la valutazione. 

Grazie

**Comment by mmelega-icteam** [comment]
Il sistema operativo è Linux. Per il dettaglio de serve devo chiedere al cliente non avendo accesso alle macchine.
In allegato l'estratto della tabella con il campo short_context  e di seguito il link al log autorizzato (https://drive.google.com/file/d/1DJKLy4uWDssTbAI-qNfI_rnn_nHy_gKs/view?usp=sharing).

Lo zip contiene anche lo stdout della shell lanciata.

Una integrazione sul comportamento rilevato. A valle del processamento del file CSTAR.03111.TRNLOG.20210101.120000.666.CSV, oltre quanto già descritto, nella folder resources/archive/success non c'è traccia del file processato, però sono presenti il file pan e par scaricati ed alcuni file temporanei

Grazie

[batch_job_execution_context.xlsx](https://github.com/pagopa/rtd-ms-transaction-filter/files/6706917/batch_job_execution_context.xlsx)

**Comment by alessio-cialini-sia** [comment]
I dati sono in fase di verifica, manderò aggiornamenti appena ho una definizione conclusiva. Grazie

**Comment by alessio-cialini-sia** [comment]
Sarebbe utile avere il contenuto della tabella BATCH_JOB_EXECUTION_CONTEXT, per ulteriori verifiche.

Grazie

**Comment by mmelega-icteam** [comment]
Le righe della tabella BATCH_JOB_EXECUTION_CONTEXT relative ai due job sono state già allegate, mio precedente commento. E' necessaria l'intera tabella?
Attenzione però che è un ambiente di test.

**Comment by alessio-cialini-sia** [comment]
Da verificare il contenuto anche della BATCH_JOB_EXECUTION_PARAMS, avrei bisogno che siano estratti i valori associati alle cartelle temporanee generate, in particolare tempOutputPath, innerOutputPath, workingParDirectory, workingHpanDirectory, che dovrebbero essere presenti come parametri del job

**Comment by mmelega-icteam** [comment]
In allegato il contenuto della BATCH_JOB_EXECUTION_PARAMS.
[batch_job_execution_params.xlsx](https://github.com/pagopa/rtd-ms-transaction-filter/files/6709068/batch_job_execution_params.xlsx)

**Comment by alessio-cialini-sia** [comment]
Vorrei richiedere eventualmente se il test di esecuzione possa essere ripetuto con i seguenti accorgimenti: file con estensione .csv (minuscolo), e pattern di lettura ACQ_BATCH_INPUT_FILE_PATTERN settato a *.csv, e venga verificato se l'elaborazione del file delle transazioni prosegue come definito.

Al fine di testare unicamente l'elaborazione del file delle transazioni, oggetto della verifica, la proprietà ACQ_BATCH_TOKEN_PAN_VALIDATION può essere settata a false per non entrare nella fase di elaborazione relativa al nuovo tracciato delle tokenizzate (Nota: configurazione da tenere solo a fini di test univocamente sul file delle transazioni)

Grazie

**Comment by mmelega-icteam** [comment]
Stiamo organizzando la ripetizione del test per questo pomeriggio. Possiamo rimuovere l'opzione root: DEBUG dal logging per renderlo più trattabile?
Grazie

**Comment by alessio-cialini-sia** [comment]
Si, dovrebbe essere più che sufficiente il DEBUG limitato alle classi dell'applicativo.

Grazie mille

**Comment by mmelega-icteam** [comment]
Abbiamo completato la riesecuzione con i parametri richiesti. A meno della necessità di intervenire nel file application yml inserendo per alcune nuove voci il prefisso "file:", il file delle transazioni CSTAR.03111.TRNLOG.20210101.120000.666.csv è stato letto correttamente: 17 righe, 14 filtrate, 3 scritte, producendo in output il file csv filtrato e pgp.

Riabilitando i valori originali delle variabili indicate il comportamento è tornato ad essere quello descritto.

Grazie

**Comment by alessio-cialini-sia** [comment]
Ok, viene confermata una piccola modifica per permettere nelle cartelle temporanee di gestire valori diversi da quelli di default. A stretto giro verrà caricata la pre-release RC2, chiederei di ripetere il test a valori originali appena disponibile la nuova versione.

Grazie

**Comment by mmelega-icteam** [comment]
Abbiamo effettuato i test con la versione rc2 con il risultato seguente.
Il file delle transazioni sottomesso CSTAR.03111.TRNLOG.20210101.120000.666.CSV, viene correttamente filtrato ed in output è generato il file finale pgp.
Il processo va però in errore sullo step "token-filter-token-list-recovery-step" con la seguente eccezione:
"feign.FeignException$Unauthorized: status 401 reading TokenPanRestConnector#getTokenList(String) ..."

L'attributo tkm.base-url è configurato con:

- domain name: https://test.cstar.pagopa.it:443
- path: /tkm/uat/acquirerm

e api key già definita per la registrazione ai servizi hpan

Sono corretti i parametri?

Grazie

**Comment by alessio-cialini-sia** [comment]
Ciao, per il recupero della lista token deve essere fatta richiesta al prodotto TKM UAT API, nel developer portal (Stessa procedura utilizzata per la prima chiave di sottoscrizione).

Dato che il problema sulle transazione viene considerato risolto nella RC2, chiederei eventualmente di ripetere eventuali richieste inerenti al processo delle tokenizzate in una pagina dedicata.

Grazie.
