### ISSUE TITLE
Richiesta chiarimenti gestione JOB.  Versione 2.0.0 - RC2

### ISSUE THREAD

**Issue by NavaA-nexi** [pagopa/rtd-ms-transaction-filter#104]
Buongiorno,

siamo a richiedere alcuni chiarimenti circa il funzionamento della nuova versione del batch 2.0.0 - RC2 e in particolare come vengono gestiti i job.

Nelle versioni precedenti ad ogni elaborazione era associato un unico JOB_EXECUTION_ID mentre in questa nuova versione ad ogni lancio vediamo che vengono creati più job
e non è chiaro il comportamento.

Tra l'altro notiamo che il download del file degli HPAN viene ripetuto ad ogni JOB.

Si allega un esempio di quanto rilevato

Grazie

[LOG V 2.0.0 -RC2 - 20210628.xlsx](https://github.com/pagopa/rtd-ms-transaction-filter/files/6726933/LOG.V.2.0.0.-RC2.-.20210628.xlsx)

**Comment by alessio-cialini-sia** [comment]
Ciao,

Come indicato nel README, il processo di elaborazione è stato modificato per ottimizzazioni, limitando la lettura degli hpan a volumi fissi e configurabili, per cui sono eseguiti più job intermedi, sulla base del volume dei file, e dei blocchi configurati.

I file NON vengono scaricati più volte, i task relativi al download sono:

transaction-filter-salt-hpan-list-recovery-step
transaction-filter-par-list-recovery-step
transaction-filter-salt-recovery-step

Tutte le altre letture, sono operazioni di salvataggio in memoria, ripetute per i job necessari al completamente sui blocchi di dimensione configurata nelle proprietà indicate sul README

**Comment by alessio-cialini-sia** [comment]
Per quanto riguarda l'ultimo blocco indicato nel file, è lo step iniziale della fase relativa alle tokenizzate, presumo sia l'unico scritto per via della mancata prosecuzione dell'elaborazione. La logica indicata sopra sarà valida anche per gli step della seconda fase di elaborazione.

**Comment by NavaA-nexi** [comment]
Ciao Alessio,
potresti cortesemente indicarci il punto del README dove è presente l'indicazione che l'ottimizzazione ha impatto sulla creazione di nuovi JOB con conseguente impatto sui log?  Grazie

**Comment by alessio-cialini-sia** [comment]
Riporto dal paragrafo relativo al logging nel README:

Starting from version 2.0.0 the batch process executes a series of jobs to produce the final output, the number of which depens to the configuration regarding the maximum number of records that can be stored in-memory, and the file volume used in the process. The count are to be considered as the grouping of all the executions for a particular file, for the transaction file production the number of records 'written' has to be considered as the difference between the number of filtered records counted in the last execution for a file, and the sum of all the previously written records.

Viene inoltre trattata la soluzione di ottimizzazione nel paragrafo Memory Optimization, sempre nel README
