### ISSUE TITLE
Apple Pay and Google Pay

### ISSUE THREAD

**Issue by gimillan** [pagopa/rtd-ms-transaction-filter#13]
If a cardholder own a credit card registered on Apple Pay or Google Pay, this means that in the Acquirer clearing file, we don't have the phisical PAN but the token registerd on Apple Pay or Google Pay. In this case the cardholder should register all both the phisical PAN number and the token on the centro Stella ?  If not how will be managed the filtering of the transactions that should be sent to  the Centro Stella ?

**Comment by alessio-cialini-sia** [comment]
Yes, in case of ApplePay/Google Pay the information of the physical PAN and the Token will be registered and saved on CentroStella (the data will be hashed). Therefore, it will be possibile to filter the transactions received from the Acquirer based on the registred token.
