### ISSUE TITLE
tipo_operazione

### ISSUE THREAD

**Issue by gimillan** [pagopa/rtd-ms-transaction-filter#14]
On the RTD Acquirer interface document, the field : tipo_operazione has the following possible values 

00 - pagamento
01 - storno pagamento
02 -pagamento con applePay
03 - pagamento con GooglePay
xx - usi futuri

if we are able to send yo only 00 and 01, but if we are not able to do not indicate if is applepay or googlepay, is it a problem ?

**Comment by alessio-cialini-sia** [comment]
No, it doesn't cause any problems for the correct functioning of the process.
