### ISSUE TITLE
Nomi variabili di ambiente in Appendice 2

### ISSUE THREAD

**Issue by alessiosassu** [pagopa/rtd-ms-transaction-filter#19]
Salve, 

volevo segnalare che i nomi delle variabili di ambiente segnalati in Appendice 2, ovvero quelli che fanno riferimento alla connessione al DB, non sono coerenti con quelli segnalati nel file application.yml di esempio.
Ad esempio nel file application.yml è indicato "ACQ_BATCH_DB_CONN_URL", mentre in Appendice 2 è indicato "BATCH_DB_CONN_URL".

Segnalo inoltre, nella stessa sezione, un refuso per cui per la chiave "spring.datasource.password" è indicato "BATCH_DB_USERNAME".

Grazie,
Alessio

**Comment by alessio-cialini-sia** [comment]
Risolto in commit #f7f8009

**Comment by alessiosassu** [comment]
Grazie, segnalo che il problema sussiste anche per la parte SFTP. In particolare trovo:

SFTP_REMOTE_DIR nel README.md
SFTP_DIRECTORY nel file application.yml

**Comment by alessio-cialini-sia** [comment]
risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/c0b397a59a3ed43bcdd252e68924c07a9330cee0
