### ISSUE TITLE
Verifica funzionamento Batch - deleteOutputFiles

### ISSUE THREAD

**Issue by NavaA-nexi** [pagopa/rtd-ms-transaction-filter#20]
Buongiorno,

da alcuni test interni è emerso il seguente comportamento del batch che vorremo verificare con voi:

Attraverso l'opzione  deleteOutputFiles è possibile gestire la cancellazione dei file di output.

Quello che abbiamo notato è questo:

Scenario1:
• impostazione deleteOutputFiles: ${ACQ_BATCH_DELETE_LOCAL_FILE:ERROR} 
• il file A viene processato correttamente => viene creato il file /output/A
• il file B viene processato con errore => non viene creato il file B; viene ripulita l'intera cartella output.

Quindi, nel caso in cui il file A non sia ancora stato inviato via SFTP al centrostella, se l'elaborazione del file B fallisce, anche il file A viene eliminato.

Scenario2:
• impostazione deleteOutputFiles: ${ACQ_BATCH_DELETE_LOCAL_FILE:KEEP} 
• il file A viene processato correttamente => viene creato il file /output/A
• il file B viene processato con errore => viene creato il file /output/B (dalle  nostre verifiche sembra che il file B venga generato vuoto) 

In questo caso al  centrostella viene inviato sia il file A che il file B  (lato Nexi non usiamo la funzione sFTP del batch ma usiamo l'sFTP interno Nexi).

Nello scenario 1 quindi perdiamo un file mentre nello scenario 2 inviamo un file errato.

Alla luce di questo siamo a  chiedere se
1) il comportamento che abbiamo rilevato trova riscontro con quanto da voi implementato
2) è possibile modificare il batch in maniera tale che in caso di errore venga eliminato solamente il file oggetto di errore e non l'intero contenuto della cartella out

Grazie

**Comment by alessiosassu** [comment]
Buonasera,

solo per indicare che anche da parte nostra c'è interesse a comprendere esattamente il funzionamento.
In particolare vorremmo capire se **ACQ_BATCH_DELETE_LOCAL_FILE** è un flag che influenza solo la cancellazione dei file di output o anche di quelli di input.

Grazie

**Comment by alessio-cialini-sia** [comment]
Il comportamento indicato è quello corretto, deleteOutputFile regola la cancellazione del contenuto della cartella di output secondo le regole riportate, al momento il comportamento non prevede una cancellazione limitata ad un singolo file. La possibilità d'introdurre questa modifica verrà verificata.

Modificare il riferimento dell'application.yml d'esempio da **ACQ_BATCH_DELETE_LOCAL_FILE**  a **ACQ_BATCH_DELETE_OUTPUT_FILE**, la modifica sarà riportata nella configurazione d'esempio.

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/b9e1f14f3f449a57d57aece94024df483145af2f
