### ISSUE TITLE
Info su comportamento properties

### ISSUE THREAD

**Issue by gaetanobasilicoaxepta** [pagopa/rtd-ms-transaction-filter#21]
Le properties/variabili di ambiente indicate di seguito fanno riferimento al path dei file in input (quindi file di transazioni e hashpan) oppure al file in output (file generato contenente il risultato dell'elaborazione)?

ACQ_BATCH_SUCCESS_PATH
ACQ_BATCH_ERROR_PATH

**Comment by alessio-cialini-sia** [comment]
Le variabili indicate regolano i percorsi dove i file utilizzati in input saranno spostati, se il batch acquirer è configurato in tal senso, in delle cartelle di "archivio" per i file processati con successo od errore.

**Comment by alessiosassu** [comment]
I file vengono archiviati comunque, anche nel caso in cui la variabile "ACQ_BATCH_DELETE_LOCAL_FILE" sia settata a ERROR (o a KEEP)?

**Comment by alessio-cialini-sia** [comment]
i file delle transazioni saranno archiviati sempre, a meno che la proprietà di cancellazione dei file locali non sia abilitata (ACQ_BATCH_DELETE_LOCAL_FILE settato a true). Le valorizzazioni sopra indicate sono per la proprietà ACQ_BATCH_DELETE_OUTPUT_FILE.
