### ISSUE TITLE
Errore di sintassi su application.yml di esempio

### ISSUE THREAD

**Issue by alessiosassu** [pagopa/rtd-ms-transaction-filter#22]
Salve,

volevo segnalare che a riga 91 del file application.yml c'è un errore di sintassi per la properties seguente:

`checksumFilePattern: ${ACQ_BATCH_HPAN_LIST_CHECKSUM_FILE_PATTE
`
Risulta infatti mancare la parentesi graffa di chiusura.

Grazie,
Alessio

**Comment by alessio-cialini-sia** [comment]
risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/c0b397a59a3ed43bcdd252e68924c07a9330cee0
