### ISSUE TITLE
Refuso documentazione README.md

### ISSUE THREAD

**Issue by sturano** [pagopa/rtd-ms-transaction-filter#23]
Nel capitolo "REST Services Connection" si fa riferimento al parametro "batchConfiguration.TransactionFilterBatch.hpanList" mentre penso sia da riferire al "batchConfiguration.TransactionFilterBatch.hpanListRecovery".

**Comment by alessio-cialini-sia** [comment]
risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/c0b397a59a3ed43bcdd252e68924c07a9330cee0
