### ISSUE TITLE
Benchmark - speed too slow

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#24]
Hi,
Processing a 1,000,000 transaction file takes nearly two hours.
The configuration used is the default one:

partitionerSize: ${ACQ_BATCH_INPUT_PARTITIONER_SIZE:10}
chunkSize: ${ACQ_BATCH_INPUT_CHUNK_SIZE:1000}

from the log, however, I always see only ONE running partition (0).
What is the average processing speed? How many transactions per hour?
Can I change the configuration to increase the number of threads?

Thanks

**Comment by alessio-cialini-sia** [comment]
The following configuration properties to manage the partion for a single file are the following:

batchConfiguration.TransactionFilterBatch.readerMaxPoolSize: ${ACQ_BATCH_INPUT_PART_READ_MAX_POOL_SIZE:5}
batchConfiguration.TransactionFilterBatch.readerCorePoolSize: ${ACQ_BATCH_INPUT_PART_READ_CORE_POOL_SIZE:5}

**Comment by alessio-cialini-sia** [comment]
The 1.000.000 transactions are all processed to the final output file, or there are errors, or filtered ones?

**Comment by mripari** [comment]
All transactions were produced in output without errors.

**Comment by mripari** [comment]
Hi,
could you please give us a little explanation on how those parameters works?
(or even you can possibly indicate the part of the documentation relating to these parameters)
thanks

**Comment by alessio-cialini-sia** [comment]
The parameters readerMaxPoolSize and readerCorePoolSize are used to define how many threads the pool related to processing chunks from a single file, the number of records within the chunk are configured by the following property: **batchConfiguration.TransactionFilterBatch.transactionFilter.chunkSize**

Please refer to the table withing the README.md for further informations about the configuration properties, or follow the spring batch manual for further details for chunking and partitioning: https://docs.spring.io/spring-batch/docs/current/reference/html/scalability.html#scalability

**Comment by mripari** [comment]
Thanks for the explanation.
As I said earlier, we are facing performance issues and it would help us to have a baseline of what we should expect in terms of speed. Is there an official benchmark for the application?
thanks again.

**Comment by alessio-cialini-sia** [comment]
Perforance improvements are under evaluation, i'd suggest to wait the next release before attempting another test

**Comment by mripari** [comment]
ok, thanks.

**Comment by alessio-cialini-sia** [comment]
Solved in https://github.com/pagopa/rtd-ms-transaction-filter/commit/5b9220391d9c1253e34d2fdc253f28669e916069
