### ISSUE TITLE
 No transaction file has been found on configured path: file:resources/transactions

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#240]
Good morning,
I receive this error message:   No transaction file has been found on configured path
but in the folder there are two file: one with .csv extension and the other with .CSV extension

below my configuration and attached the application.yml
  transactionFilter:
      transactionDirectoryPath: file:${ACQ_BATCH_TRX_INPUT_PATH:resources/transactions}/

Please may you help me?
Thank you

**Comment by and-mora** [comment]
Hi, please make sure to respect the naming convention for the input files. You can find the reference [here](https://docs.pagopa.it/centrostella-1/centro-stella/instructions-for-agenzia-delle-entrate-mandate/appendixes/appendix-2-input-file-specifications) (e.g. CSTAR.12345.TRNLOG.20220919.090600.001.csv). 
Files with wrong naming convention will be ignored.

**Comment by s77937** [comment]
transactionDirectoryPath: file:${ACQ_BATCH_TRX_INPUT_PATH:resources/transactions}/${ACQ_BATCH_INPUT_FILE_PATTERN:*.CSV}

I've configured this property in this way, because our input files have this extension.

But the error message is always "No transaction file has been found on configured path: file:resources/transactions/*.CSV", but the file with CSV extention exists.
