### ISSUE TITLE
Utilizzo driver Oracle

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#25]
Ciao,
avremmo bisogno di supporto per la configurazione del batch.

La prima difficoltà che riscontriamo è relativa all'utilizzo del driver oracle.
Abbiamo seguito le indicazioni, effettuato il build del progetto, ma quando lo lanciamo con la specifica del classpath che punta alla locazione del jar del driver otteniamo errore:
nested exception is java.lang.IllegalStateException: Cannot load driver class: oracle.jdbc.OracleDriver

Effettuando un po' di scouting, sembrerebbe che le opzioni -jar e -cp, come indicate nel readme, non siano compatibili, vedi:
stackoverflow.com/questions/15930782/call-java-jar-myfile-jar-with-additional-classpath-option

Abbiamo momentaneamente risolto modificando uno dei pom e facendo includere ojdbc8.jar nel jar generato.
Potreste verificare se le indicazioni del readme per il lancio con driver "custom" sono corrette?

Grazie.

**Comment by alessio-cialini-sia** [comment]
Provate ad usare il seguente comando:

java -cp "batch-transaction-filter.jar;ojdbc8.jar" -Dloader.main=RtdTransactionFilterApplication org.springframework.boot.loader.PropertiesLauncher -jar .\batch-transaction-filter.jar --spring.config.location=file:config\
