### ISSUE TITLE
Errore per ORA-00942: table or view does not exist

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#26]
Ciao,
una volta generato il jar (con incluso ojdbc8.jar, vedi issue #25) abbiamo creato le tabelle sul database oracle ma otteniamo un errore relativo a tabella o vista non esistente:
java.sql.SQLSyntaxErrorException: ORA-00942: table or view does not exist

La lista delle tabelle create su database è la seguente:

TABLE LOGGING_EVENT
TABLE LOGGING_EVENT_PROPERTY
TABLE LOGGING_EVENT_EXCEPTION
TABLE BATCH_JOB_INSTANCE
TABLE BATCH_JOB_EXECUTION
TABLE BATCH_JOB_EXECUTION_PARAMS
TABLE BATCH_STEP_EXECUTION
TABLE BATCH_STEP_EXECUTION_CONTEXT
TABLE BATCH_JOB_EXECUTION_CONTEXT

Potreste indicarci se sono tutte le tabelle necessarie all'esecuzione dell'applicazione?

Grazie.

**Comment by alessio-cialini-sia** [comment]
Le tabelle da utilizzare sono quelle definite negli script inclusi in:

- /ops_resources/logback_scripts, se inteso utilizzare la configurazione del logback
- /ops_resources/batch_scripts, per le tabelle del batch

Utilizzare lo script corrispondente al vendor utilizzato, e configurare le proprietà per la connessione al database riportate in tabella.

Nel caso di persistenza di errori fornire configurazione e log completo.

**Comment by t005627** [comment]
Ciao, 
innanzitutto grazie per il supporto e la celere risposta.
Le tabelle sono state create con gli script indicati.
Allego il log ed il file application.yml (a cui ho aggiunto l'estensione txt).
Sottolineo che nel file ho modificato alcune informazioni "sensibili" (es. indirizzo DB / user / password / schema / alcuni path).
Nel log sono anche presenti errori successivi, ma vorrei per prima cosa risolvere il problema sul db oracle.

Una cosa che noto nel log che non mi torna è la seguente riga:
2020-10-07 09:32:02.013  INFO 10859 --- [           main] org.hibernate.dialect.Dialect            : HHH000400: Using dialect: org.hibernate.dialect.HSQLDialect

Ho impostato nel file application.yml il dialetto oracle "org.hibernate.dialect.OracleDialect" ma la proprietà non sembra essere letta correttamente. 
Non so se questo è correlato all'errore o meno.

Vi ringrazio per il supporto.
(url
[log.txt](https://github.com/pagopa/rtd-ms-transaction-filter/files/5339665/log.txt)
[application.yml.txt](https://github.com/pagopa/rtd-ms-transaction-filter/files/5339668/application.yml.txt)

)

**Comment by alessio-cialini-sia** [comment]
Provate ad eseguire il seguente comando:

java -cp "batch-transaction-filter.jar;ojdbc8.jar" -Dloader.main=RtdTransactionFilterApplication org.springframework.boot.loader.PropertiesLauncher -jar .\batch-transaction-filter.jar --spring.config.location=file:config\

Dove la spring config location dovrà corrispondere alla locazione del vostro application.yml

**Comment by t005627** [comment]
Su una macchina unix (specifico per giustificare l'utilizzo di "/" invece di "\" ), ho provato ad eseguire il seguente comando dall'interno della directory "rtd-ms-transaction-filter" (in cui sono presenti sia "batch-transaction-filter.jar" che "ojdbc8.jar").

/usr/jdk/instances/jdk1.8.0/bin/java -cp "batch-transaction-filter.jar;ojdbc8.jar" -Dloader.main=RtdTransactionFilterApplication org.springframework.boot.loader.PropertiesLauncher -jar ./batch-transaction-filter.jar --spring.config.location=/rtd-ms-transaction-filter/resources/config/

Nota: il file application.yml è presente in /rtd-ms-transaction-filter/resources/config/

Ottengo però il seguente errore immediatamente :
Error: Could not find or load main class org.springframework.boot.loader.PropertiesLauncher

**Comment by t005627** [comment]
Sono riuscito a lanciare il batch con il seguente comando:
/usr/jdk/instances/jdk1.8.0/bin/java -cp "batch-transaction-filter.jar:ojdbc8.jar" -Dloader.main=it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication org.springframework.boot.loader.PropertiesLauncher -jar ./batch-transaction-filter.jar --spring.config.location=/rtd-ms-transaction-filter/resources/config/

Sostituendo:

"batch-transaction-filter.jar;ojdbc8.jar"
con 
"batch-transaction-filter.jar:ojdbc8.jar"

e 
-Dloader.main=RtdTransactionFilterApplication
con 
-Dloader.main=it.gov.pagopa.rtd.transaction_filter.RtdTransactionFilterApplication 

Ora il batch, differentemente da prima, riesce a caricare il driver oracle.
Ottengo però ancora l'errore : ORA-00942: table or view does not exist

**Comment by t005627** [comment]
Ciao,
sono riuscito a far caricare il Dialect corretto ed il problema si è risolto.
Il comando corretto da utilizzare mi risulta comunque quello che ho messo nel commento precedente.
Grazie.
