### ISSUE TITLE
503 Service Unavailable

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#261]
Ciao,
sembra che il servizio non sia disponibile. Per favore potreste verificare?
Grazie
feign.FeignException$ServiceUnavailable: [503 Service Unavailable] during [GET] to [https://api.uat.cstar.pagopa.it:443/rtd/payment-instrument-manager/salt] [HpanRestConnector#getSalt(String)]: [<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
]

**Comment by TommasoLencioni** [comment]
@s77937 possiamo chiudere la issue?

**Comment by s77937** [comment]
Sì grazie

Da: Tommaso Lencioni ***@***.***>
Inviato: mercoledì 19 ottobre 2022 11:23
A: pagopa/rtd-ms-transaction-filter ***@***.***>
Cc: s77937 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [pagopa/rtd-ms-transaction-filter] 503 Service Unavailable (Issue #261)


Caution! External email. Do not open attachments or click links, unless this email comes from a known sender and you know the content is safe.

@s77937<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fs77937&data=05%7C01%7Cmarco.maglione%40worldline.com%7C1c2933b08d884863d32e08dab1b382c6%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017681796009069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=oZ9D3PW1Zt3uBEF6VyjWdwK9wRdKXRDlx8ZmxrDyl8g%3D&reserved=0> possiamo chiudere la issue?

-
Reply to this email directly, view it on GitHub<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F261%23issuecomment-1283696986&data=05%7C01%7Cmarco.maglione%40worldline.com%7C1c2933b08d884863d32e08dab1b382c6%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017681796009069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=nAivptgFKFGvXV09pyUX8Z6x7aRQxlLU1iSTiZ8MQ%2BI%3D&reserved=0>, or unsubscribe<https://fra01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAR3RTBP32IGHX3O2GAW4FNTWD64W7ANCNFSM6AAAAAARBNRTEU&data=05%7C01%7Cmarco.maglione%40worldline.com%7C1c2933b08d884863d32e08dab1b382c6%7Cfda9decfe89243ac9d9f1a493f9f98d0%7C0%7C0%7C638017681796009069%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=4b0D7%2BmT8DiR6tHypLcypE%2F%2BbJY4hWwllIfHgl506RY%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.******@***.***>>

Worldline, Cardlink, GoPay and Santeos are registered trademarks and trade names owned by the Worldline Group. This e-mail and any documents attached are confidential and intended solely for the addressee. It may also be privileged. If you are not the intended recipient of this e-mail, you are not authorized to copy, disclose, use or retain it. Please notify the sender immediately and delete this e-mail (including any attachments) from your systems. As e-mails may be intercepted, amended or lost, they are not secure. Therefore, Worldline's and its subsidiaries' liability cannot be triggered for the message content. Although the Worldline Group endeavors to maintain a virus-free network, we do not warrant that this e-mail is virus-free and do not accept liability for any damages, losses or consequences resulting from any transmitted virus if any. The risks are deemed to be accepted by anyone who communicates with Worldline or its subsidiaries by e-mail.
