### ISSUE TITLE
Test UAT - 6b.Compare the expected test AdE error file with the downloaded one

### ISSUE THREAD

**Issue by gbasilico** [pagopa/rtd-ms-transaction-filter#266]
Abbiamo configurato l'ambiente seguendo la guida step-by-step con installazione Docker.
Non riusciamo a completare il test UAT 6b in quanto non viene scaricato il files all'interno della directory /PATH/TO/BATCH_SERVICE/ADE_ERROR/DIRECTORY correttamente impostato dalla variabile di ambiente ACQ_BATCH_SENDER_ADEACK_OUTPUT_PATH=/workdir/ade-errors

Cosa possiamo verificare?

**Comment by TommasoLencioni** [comment]
Buonasera,
vi invitiamo riprovare una run del Batch Service.
Ai fini del test non occorre che eseguite lo script 005b, sarà sufficiente che abbiate disponibili almeno 7 files nella cartella /workdir/ade-errors (tutti con nome conforme a `ADEACK.01005.01005.2022-10-*`).

**Comment by TommasoLencioni** [comment]
@gbasilico possiamo chiudere la issue?
