### ISSUE TITLE
Chiave rest-client.hpan.api.key non è dinamica nel file application.yml

### ISSUE THREAD

**Issue by alessiosassu** [pagopa/rtd-ms-transaction-filter#27]
Buongiorno, 

volevo segnalare che nel file di esempio "application.yml" la chiave di configurazione "rest-client.hpan.api.key" a riga 116 è settata staticamente a "test".
Riteniamo che debba essere anche qui utilizzata una variabile, del tipo:

`
      key: ${HPAN_SERVICE_API_KEY:test}
`

Grazie

**Comment by alessio-cialini-sia** [comment]
risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/c0b397a59a3ed43bcdd252e68924c07a9330cee0

**Comment by alessiosassu** [comment]
grazie
