### ISSUE TITLE
Quali file sono soggetti a cifratura/decifratura

### ISSUE THREAD

**Issue by alessiosassu** [pagopa/rtd-ms-transaction-filter#28]
Salve,

volevo un chiarimento sul funzionamento delle variabili seguenti

```
ACQ_BATCH_INPUT_PUBLIC_KEYPATH
ACQ_BATCH_INPUT_SECRET_KEYPATH
```

In particolare volevo capire se queste variabili devono puntare alla coppia di chiavi (privata/pubblica) create tramite il processo di enrollment che parte dalla compilazione della CSR seguente: [CSR](https://github.com/pagopa/rtd-ms-transaction-filter/blob/master/ops_resources/certificate/client-certificate.cnf).

Inoltre, volevo sapere se le chiavi da importare nel file JKS (nel caso in cui "HPAN_SERVICE_MTLS_ENABLED" sia valorizzato a "true") sono le stesse governate dalle due variabili "ACQ_BATCH_INPUT_PUBLIC_KEYPATH" e "ACQ_BATCH_INPUT_SECRET_KEYPATH".

Grazie

**Comment by alessio-cialini-sia** [comment]
Le chiavi indicate sono rispettivamente chavi pubblica e privata per l'encrypt/decrypt dei file in pgp, i file jks sono store per la gestione della mutua autenticazione, e sono configurabili tramite le proprietà riportate nel blocco della tabella per la connessione REST, oppure nel paragrafo **REST Services Connection**

**Comment by alessiosassu** [comment]
Grazie del chiarimento. 
Considerando quindi che le variabili:
ACQ_BATCH_INPUT_PUBLIC_KEYPATH
ACQ_BATCH_INPUT_SECRET_KEYPATH
fanno riferimento alla cifratura PGP, volevo sapere come deve essere comunicata/fornita la chiave PGP.
Grazie

**Comment by alessio-cialini-sia** [comment]
La chiave pubblica per l'encypt è disponibile nel documento RTD Acquirer Interface, disponibile nella directory ops_resources del repository.
