### ISSUE TITLE
Registrazione Virtual PAN Google Pay o Apple Pay

### ISSUE THREAD

**Issue by gimillan** [pagopa/rtd-ms-transaction-filter#29]
Buongiorno,
per i titolari che utilizzano applepay o googlepay, dovranno registrare sia i PAN delle carte fisiche, che i PAN dei Token associati ?
In caso affermativo, dove può reperire il titolare il PAN del Token ?
O viceversa questa attività è a carico degli Issuer ?

**Comment by menottistefano** [comment]
Ciao,
per la partenza 01/12/20 non sarà possibile enrollare i PAN tokenizzati utilizzati nelle transazioni con Apple e Google Pay.
sarà oggetto di integrazione successiva in carico all'App IO e/o agli issuer.
è fondamentale però che lato acquirer anche queste transazioni siano inviate e trattate come le transazioni con carta fisica, e inserite nel file elaborato in input dal batch acquirer
