### ISSUE TITLE
Compliance allo standard PCI DSS

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#30]
Ciao,
vorrei una conferma sul fatto che il sorgente sia stato sottoposto ad una verifica di compliance allo standard PCI DSS.
In caso negativo, possiamo procedere noi in autonomia all'analisi?
Grazie.

**Comment by menottistefano** [comment]
Ciao,
la certificazione PCI-DSS non comprende solo l’analisi del codice, pertanto non può essere condotta da PagoPa dato che il software è open source e rilasciato all’interno dell’ambiente/infrastruttura del soggetto acquirer.
Procedete pure in autonomia con l'analisi, se ci fossero segnalazioni vi chiedo la cortesia di condividerle ed eventualmente contribuire alla comunity ;-)
GRAZIE
