### ISSUE TITLE
Modifica livello logging

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#31]
Buongiorno,

Sarebbe possibile modificare la strategia di logging nella tabella "logging_event" in modo che, per il livello "INFO", vengano loggate tutte le operazioni svolte dall'applicazione, compresi i periodici tentativi di lettura dei file nella cartella "transactions", ma non ogni singola riga processata/filtrata?

Grazie.

Mauro

**Comment by alessio-cialini-sia** [comment]
La gestione del logging è in fase di valutazione, e sarà disponibile la revisione nella prossima release.

**Comment by alessio-cialini-sia** [comment]
Solved in https://github.com/pagopa/rtd-ms-transaction-filter/commit/5b9220391d9c1253e34d2fdc253f28669e916069
