### ISSUE TITLE
Segnalazioni documentazione

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#32]
Ciao, 
nel paragrafo "Database connection" del readme si fa riferimento alle costanti da usare per il livello di isolamento su Oracle.
Nelle costanti menzionate manca però la lettera "T".
ISOLAION_READ_COMMITTED --> ISOLATION_READ_COMMITTED
ISOLAION_READ_UNCOMMITTED --> ISOLATION_READ_UNCOMMITTED

Sempre nella documentazione, si fa riferimento al parametro spring.batch.job.scheduled che non è però presente nell'application.yml presente in rtd-ms-transaction-filter/ops_resources/example_config/

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/db09de1c43d4675d064b9e059cd9e2235bad529b
