### ISSUE TITLE
Client certificate

### ISSUE THREAD

**Issue by t005491** [pagopa/rtd-ms-transaction-filter#33]
Hello. We are having a doubt about the client certificate. Following the instructions at the "Appendice 7" of RTD_Acquirer_Interface document, we have configured the truststore with the server certificates, and the keystore generating a self-signed certificate (we are in SIT environment) using the client-certificate.cnf template. We have also created the auth-key on the portal. When the batch starts, all is ok about the loading of keystore and truststore, but when we call the REST service, we are getting

HTTP/1.1 403 No Certificate Found

Same result if we use a stand-alone simple client developed in order to investigate the cause of this response.
About the client self-signed certificate, we have to provide it in some way (in order to get it recognized on the server side)?
Best regards

**Comment by alessio-cialini-sia** [comment]
The following error occurs when the request is not passing through any certificate. If the keystore is correctly configured with a valid certificate, please ensure that any intermediate network element (such as a corporate proxy) is not blocking a correct TLS Handshake.

**Comment by t005491** [comment]
We have checked our configuration in order to be sure to send client certificate. We send it, and we have made a dump to check the TLS connection setup. It has been completed:

...
check handshake state: finished[20]
update handshake state: finished[20]
*** Finished
...

We are getting, at application level:

HTTP/1.1 403 Certificate not verified

instead of "No Certificate Found".
The client certificate is self-signed, we have to provide it in some way (in order to get it recognized on the server side)?
Best regards

**Comment by alessio-cialini-sia** [comment]
If you have not already sent a self-signed certificate, please provide a .pfx file (with passphrase), alongside with .cer files for the root and intermidiate CA.

To speed up the process, in this instance, send it to this mail address: cons.CialiniAlessio@sia.eu

**Comment by t005491** [comment]
Hello. We have sent the certificate and related stuff at the mentioned email.
Thanks for the support, best regards
