### ISSUE TITLE
Exception: java.net.UnknownHostException: BATCH

### ISSUE THREAD

**Issue by gaetanobasilicoaxepta** [pagopa/rtd-ms-transaction-filter#34]
`12/10/2020 18:04:162020-10-12 18:04:16.848  INFO 14 --- [rTaskExecutor-2] o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-worker-step:partition0] executed in 107ms
12/10/2020 18:04:162020-10-12 18:04:16.862  INFO 14 --- [ask-scheduler-1] o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-master-step] executed in 155ms
12/10/2020 18:04:162020-10-12 18:04:16.903  INFO 14 --- [ask-scheduler-1] o.s.batch.core.job.SimpleStepHandler     : Executing step: [transaction-sender-master-step]
12/10/2020 18:04:172020-10-12 18:04:17.039 ERROR 14 --- [rTaskExecutor-3] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-filter-send-step in job transaction-filter-job
12/10/2020 18:04:17
12/10/2020 18:04:17org.springframework.integration.util.PoolItemNotAvailableException: Failed to obtain pooled item
12/10/2020 18:04:17 at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:181) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.session.CachingSessionFactory.getSession(CachingSessionFactory.java:132) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.RemoteFileTemplate.execute(RemoteFileTemplate.java:432) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:298) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:286) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.RemoteFileTemplate.send(RemoteFileTemplate.java:278) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.handler.FileTransferringMessageHandler.handleMessageInternal(FileTransferringMessageHandler.java:205) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.handler.ReplyProducingMessageHandlerWrapper.handleRequestMessage(ReplyProducingMessageHandlerWrapper.java:49) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.handler.AbstractReplyProducingMessageHandler.handleMessageInternal(AbstractReplyProducingMessageHandler.java:127) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.dispatcher.AbstractDispatcher.tryOptimizedDispatch(AbstractDispatcher.java:115) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.dispatcher.UnicastingDispatcher.doDispatch(UnicastingDispatcher.java:133) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.dispatcher.UnicastingDispatcher.dispatch(UnicastingDispatcher.java:106) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:403) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:151) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.messaging.core.AbstractMessageSendingTemplate.convertAndSend(AbstractMessageSendingTemplate.java:143) ~[spring-messaging-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.gateway.MessagingGatewaySupport.send(MessagingGatewaySupport.java:429) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.gateway.GatewayProxyFactoryBean.sendOrSendAndReceive(GatewayProxyFactoryBean.java:628) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.gateway.GatewayProxyFactoryBean.invokeGatewayMethod(GatewayProxyFactoryBean.java:549) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.gateway.GatewayProxyFactoryBean.doInvoke(GatewayProxyFactoryBean.java:524) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.gateway.GatewayProxyFactoryBean.invoke(GatewayProxyFactoryBean.java:513) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at com.sun.proxy.$Proxy95.sendToSftp(Unknown Source) ~[na:na]
12/10/2020 18:04:17 at it.gov.pagopa.rtd.transaction_filter.connector.TransactionSftpConnector.sendFile(TransactionSftpConnector.java:17) ~[rtd-ms-transaction_filter-integration-sftp-1.0.0-RC7.jar!/:1.0.0-RC7]
12/10/2020 18:04:17 at it.gov.pagopa.rtd.transaction_filter.service.SftpConnectorServiceImpl.transferFile(SftpConnectorServiceImpl.java:22) ~[rtd-ms-transaction-filter-core-1.0.0-RC7.jar!/:1.0.0-RC7]
12/10/2020 18:04:17 at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet.execute(TransactionSenderTasklet.java:31) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
12/10/2020 18:04:17 at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet$$FastClassBySpringCGLIB$$1a3dbe1.invoke(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
12/10/2020 18:04:17 at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at it.gov.pagopa.rtd.transaction_filter.batch.step.tasklet.TransactionSenderTasklet$$EnhancerBySpringCGLIB$$5fdf9537.execute(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC7.jar!/:1.0.0-RC7]
12/10/2020 18:04:17 at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:407) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.step.tasklet.TaskletStep$ChunkTransactionCallback.doInTransaction(TaskletStep.java:331) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140) ~[spring-tx-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.repeat.support.RepeatTemplate.getNextResult(RepeatTemplate.java:375) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.repeat.support.RepeatTemplate.executeInternal(RepeatTemplate.java:215) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.repeat.support.RepeatTemplate.iterate(RepeatTemplate.java:145) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.step.tasklet.TaskletStep.doExecute(TaskletStep.java:258) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:208) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:138) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:135) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
12/10/2020 18:04:17 at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_265]
12/10/2020 18:04:17 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_265]
12/10/2020 18:04:17 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_265]
12/10/2020 18:04:17 at java.lang.Thread.run(Thread.java:748) [na:1.8.0_265]
12/10/2020 18:04:17Caused by: java.lang.IllegalStateException: failed to create SFTP Session
12/10/2020 18:04:17 at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:391) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:60) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:83) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.file.remote.session.CachingSessionFactory$1.createForPool(CachingSessionFactory.java:80) ~[spring-integration-file-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.util.SimplePool.doGetItem(SimplePool.java:191) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.util.SimplePool.getItem(SimplePool.java:172) ~[spring-integration-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 ... 60 common frames omitted
12/10/2020 18:04:17Caused by: java.net.UnknownHostException: BATCH
12/10/2020 18:04:17 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184) ~[na:1.8.0_265]
12/10/2020 18:04:17 at java.net.Socket.connect(Socket.java:607) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:962) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:924) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1019) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1005) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:311) ~[na:1.8.0_265]
12/10/2020 18:04:17 at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:417) ~[na:1.8.0_265]
12/10/2020 18:04:17 at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:173) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.initJschSession(DefaultSftpSessionFactory.java:417) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 at org.springframework.integration.sftp.session.DefaultSftpSessionFactory.getSession(DefaultSftpSessionFactory.java:379) ~[spring-integration-sftp-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
12/10/2020 18:04:17 ... 65 common frames omitted
12/10/2020 18:04:17
12/10/2020 18:04:172020-10-12 18:04:17.045  INFO 14 --- [rTaskExecutor-3] o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-send-step:partition0] executed in 108ms
12/10/2020 18:04:172020-10-12 18:04:17.054 ERROR 14 --- [ask-scheduler-1] o.s.batch.core.step.AbstractStep         : Encountered an error executing step transaction-sender-master-step in job transaction-filter-job`

**Comment by alessio-cialini-sia** [comment]
The following error seems to indicate a misconfiguration within the sftp client properties, ensure that the following properties are correctly configured within the .yml file:

__connectors.sftpConfigurations.connection.host__
__connectors.sftpConfigurations.connection.port__
__connectors.sftpConfigurations.connection.user__
__connectors.sftpConfigurations.connection.password__
__connectors.sftpConfigurations.connection.privateKey__
__connectors.sftpConfigurations.connection.passphrase__
__connectors.sftpConfigurations.connection.directory__

If the problem persists, please provide the applied application.yml.

**Comment by alessiosassu** [comment]
Di seguito le variabili di ambiente:

```
# env | grep -i sftp
SFTP_PASSPHRASE=
SFTP_LOCAL_DIR=/BATCH/files/ouput
SFTP_PRIVATE_KEY=/BATCH/keys/sftp-private.key
SFTP_REMOTE_DIR=/Inbox/
SFTP_PASSWORD=
SFTP_PORT=20022
SFTP_USER=88104
SFTP_HOST=sftp
```

Il file di configurazione è quello di esempio fornito nel presente repository github

```
# grep -i sftp application.yml
      sftp:
        localdirectory: file:${SFTP_LOCAL_DIR:resources/output}/${SFTP_FILE_PATTERN:*}
  sftpConfigurations:
      host: ${SFTP_HOST:}
      port: ${SFTP_PORT:10022}
      user: ${SFTP_USER:}
      password: ${SFTP_PASSWORD:}
      privateKey: file:/${SFTP_PRIVATE_KEY:}
      passphrase: ${SFTP_PASSPHRASE:}
      allowUnknownKeys: ${SFTP_ALLOW_UNKNOWN_KEYS:true}
      timeout: ${SFTP_TIMEOUT:5000}
      directory: ${SFTP_DIRECTORY:/}
```

**Comment by alessiosassu** [comment]
Preciso che l'alias sftp viene rimappato verso l'host effettivo di destinazione tramite DNS locale

**Comment by alessio-cialini-sia** [comment]
La riga di errore che descrive il problema è la seguente:

org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:173)

La url resource corrispondente al file non è in un formato leggibile, fare riferimento alla configurazione utilizzata per gli input delle transazioni/lista dei pan utilizzata, puntando però alla cartella utilizzata per la scrittura dei file di output.

**Comment by alessiosassu** [comment]
In seguito all'indicazione, abbiamo modificato la riga 

`      privateKey: file:/${SFTP_PRIVATE_KEY:}`

in 

`      privateKey: file:${SFTP_PRIVATE_KEY:}`

in quanto il path assoluto della chiave privata viene passato tramite variabile di ambiente già con la "/" iniziale.
Non vediamo errori in seguito alla modifica e ci risulta che il file transfer vada a buon fine.

Grazie

**Comment by alessiosassu** [comment]
Probabilmente è opportuno correggere il template del file application.yml di questo repository, in tal senso.
