### ISSUE TITLE
Documentazione Flusso Standard PagoPA

### ISSUE THREAD

**Issue by gaetanobasilicoaxepta** [pagopa/rtd-ms-transaction-filter#35]
-Nel tracciato descritto è presente il campo **hash_pan**, ma nella documentazione al capitolo **"Processo invio transazioni verso RTD"** al punto **"e"** viene descritto come se l'hash venisse fatto dal batch acquirer. 
Qual è la versione corretta?

**Comment by lucasomarugasia** [comment]
Confermiamo che l'hash del PAN è eseguito dal batch acquirer. Il tracciato in documentazione corrisponde all'output del batch acquirer. L'input al batch acquirer prevede il PAN in chiaro.
