### ISSUE TITLE
Informazioni per download flussi HPAN

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#37]
Ciao,
avremmo necessità di conoscere l'host (relativo all'ambiente di test) su cui risiederanno i flussi da scaricare, il cui link è restituito dal servizio REST.
E' un link sempre residente su bpd-dev.azure-api.net ?
Questo per procedere alle aperture di rete necessarie tra il nostro ambiente di test e le macchine/porte su cui risiedono i link dei flussi da scaricare.
Vorremmo sapere se il "formato" del link è fisso o variabile.
Se possibile, forniteci anche un esempio di link generato per il download.

Grazie.

**Comment by menottistefano** [comment]
ciao,
i puntamenti agli ambienti (SIT, UAT, PROD) sono quelli inseriti nell'appendice 8 del file /ops_resources/RTD_Acquirer_Interface_V3.pdf.

il formato del link è variabile, esposto dietro la baseurl dell'ambiente di riferimento e gestito dalla libreria.
