### ISSUE TITLE
Info tracciato Standard PagoPa

### ISSUE THREAD

**Issue by gaetanobasilicoaxepta** [pagopa/rtd-ms-transaction-filter#39]
Riscontro ricorrentemente un errore sul parsing del file che carico:

`2020-10-15 12:10:29.784 INFO 10 --- [rTaskExecutor-3] .r.t.b.s.l.TransactionItemReaderListener : #### Error while reading a transaction record - Parsing error at line: 1 in resource=[URL [file:/BATCH/files/input/transazioni/CSTAR.01005.TRNLOG.20201015.120500.003.csv]]`

A quale versione del documento devo far riferimento per compilare correttamente il file con il tracciato corretto delle transazioni?

**Comment by menottistefano** [comment]
ciao Gaetano,
a questo: rtd-ms-transaction-filter/ops_resources/RTD_Acquirer_Interface_V3.pdf
i file d'esempio li trovi qui: rtd-ms-transaction-filter/ops_resources/example_files/
