### ISSUE TITLE
ERRATO LOGGIN SU TABELLA BATCH_STEP_EXECUTION

### ISSUE THREAD

**Issue by NavaA-nexi** [pagopa/rtd-ms-transaction-filter#41]
Ciao,

vi segnalo un problema sulla versione batch-transaction-filter-1.0.0-RC8-Hotfix.jar 

Nella tabella di log BATCH_STEP_EXECUTION vengono scritte in maniera errata le numeriche relative ai record filtrati.

Da documentazione:

The table contains a series of columns containing useful information on the processed records: the read_count value details the number of successfully read lines, while the read_skip_count define the records that are skipped under the selected fault-tolerance policy. similarly, the write_count, write_skip_count and process_skip_count all retain a similar purpose in the filtering process and writing phases for the record. All the records that are in an error state, are included in the value for the rollback_count.
For the transaction filtering, the filter_count record is useful to keep track of how many transactions have been filtered, due to not matching the stored HPAN records. Filtered records are by default not included in the rollback count, as it's part of the business logic.
 
Nel nostro caso abbiamo sottoposto un file da 230.952 record e sono stati filtrati tutti i record tranne 1. Nella colonna FILTER_COUNT viene però riportato il valore 0  mentre ci saremmo aspettati 230.951.  In maniera analoga nella colonna WRITE_COUNT viene riportato il valore 230.952 mentre ci saremmo aspettati 1.

Potete cortesemente verificare?

Grazie

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/b9e1f14f3f449a57d57aece94024df483145af2f
