### ISSUE TITLE
Chiarimento properties

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#42]
Ciao,
vorrei un chiarimento sui file di properties e sul file application.yml.
Ci sono alcune proprietà che sono presenti sia in alcuni file di properties che nel file application.yml di esempio.
E' necessario che le proprietà siano presenti in entrambi?
Ossia, una proprietà può essere letta dall'applicazione da entrambi le locazioni? In quale caso?
Altrimenti, sarebbe possibile indicare quali proprietà vengono lette dal file application.yml e quali dai file di properties?
Questo per mantenere solo le proprietà realmente necessarie.
E' possibile che l'informazione sia presente nella documentazione e magari mi è sfuggita.
In quel caso, potreste indicarmi dove vedere?

Grazie

**Comment by alessio-cialini-sia** [comment]
Il file di properties di esempio è quello utilizzato esternamente, qualsiasi configurazione esterna (richiamata con il parametro di esecuzione spring.config.location) ha precedenza su quelle interne nei file .properties.

**Comment by t005627** [comment]
Ciao,
la domanda nasceva dal fatto che per far caricare il corretto Dialect, impostato tramite la proprietà database-platform, avevo dovuto modificare le properties interne e ricompilare con quelle per la produzione del jar.
Pensavo quindi che quella proprietà (e potenzialmente altre) venivano caricate dai file di properties
Ho scoperto ora che in realtà il problema è probabilmente dovuto ad una non corretta "indentatura" nel file application.yml di esempio.
La sezione "jpa" è infatti all'interno di datasource, credo dovrebbe invece essere allo stesso livello.
Modificando infatti in questo modo il file application.yml, la proprietà database-platform viene caricata correttamente dal file application.yml.

Grazie.

**Comment by alessio-cialini-sia** [comment]
Verrà verificato che l'indentatura riportata nel file di esempio sia corretta.

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/f45ef6fe51e5ad147f98b643f4d6885112f935d0
