### ISSUE TITLE
STATUS FAILED when SKIP > 0

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#43]
Ciao,

Impostando il valore 

**skipLimit: ${ACQ_BATCH_INPUT_SKIP_LIMIT:10}**

A fronte di un record scartato il processo presenta nella tabella "batch_step_execution"
STATUS = COMPLETED
EXIT_CODE = COMPLETED WITH SKIPS

mentre nella tabella "batch_job_execution" 
STATUS = COMPLETED
EXIT_CODE = FAILED

è corretto? Assumendo di tollerare degli scarti, lo stato finale non dovrebbe essere "COMPLETED" o, al più, "WARNING"

grazie

Saluti,
Mauro

**Comment by alessio-cialini-sia** [comment]
Risolto in https://github.com/pagopa/rtd-ms-transaction-filter/commit/b9e1f14f3f449a57d57aece94024df483145af2f
