### ISSUE TITLE
Errore Logging su Orace

### ISSUE THREAD

**Issue by mmelega-icteam** [pagopa/rtd-ms-transaction-filter#44]
Ciao,
attivando il logging (it.gov.pagopa.rtd.transaction_filter a DEBUG) su DB Oracle (12c Enterprise Edition Release 12.1.0.2.0 - 64bit Production) con il relativo driver ojdbc8.jar otteniamo in avvio la seguente eccezione che termina il processo:
- ERROR in ch.qos.logback.classic.db.DBAppender[SIMPLE_DB] - problem appending event java.sql.SQLException: Invalid argument(s) in call.

Dopo alcune ricerche sul problema, provando ad utilizzare il driver per java7, ojdbc7.jar, il processo sale e rimane running, inserendo correttamente il log nelle tabelle LOGGING_EVENT, ecc., ma solo se il livello di logging è INFO.
Con il livello DEBUG il processo solleva l'eccezione:
- ORA-01461: can bind a LONG value only for insert into a LONG column
senza specificare tabella o campo e termina.

Grazie

**Comment by alessio-cialini-sia** [comment]
Il jdk di riferimento, ed i driver associati, devono essere rispetto alla versione 8. Per problemi legati all'appender del logback, servirà fare riferimento alla documentazione ufficiale di quest'ultimo: http://logback.qos.ch/manual/appenders.html#DBAppender
