### ISSUE TITLE
Errore in fase di cifratura - UAT

### ISSUE THREAD

**Issue by alessiosassu** [pagopa/rtd-ms-transaction-filter#45]
Buonasera,

riscontriamo un errore nell'esecuzione del batch in ambiente UAT, relativamente alla fase di cifratura PGP:

`29/10/2020 14:30:322020-10-29 14:30:32.144  INFO 10 --- [rTaskExecutor-2] o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-worker-step:partition0] executed in 470ms
29/10/2020 14:30:322020-10-29 14:30:32.250 ERROR 10 --- [rTaskExecutor-2] o.s.batch.core.step.AbstractStep         : Exception while closing step execution resources in step transaction-filter-worker-step in job transaction-filter-job
29/10/2020 14:30:32
29/10/2020 14:30:32java.lang.IllegalArgumentException: Can't find encryption key in key ring.
29/10/2020 14:30:32	at it.gov.pagopa.rtd.transaction_filter.batch.encryption.EncryptUtil.readPublicKey(EncryptUtil.java:188) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC8.jar!/:1.0.0-RC8]
29/10/2020 14:30:32	at it.gov.pagopa.rtd.transaction_filter.batch.step.writer.PGPFlatFileItemWriter.close(PGPFlatFileItemWriter.java:49) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC8.jar!/:1.0.0-RC8]
29/10/2020 14:30:32	at it.gov.pagopa.rtd.transaction_filter.batch.step.writer.PGPFlatFileItemWriter$$FastClassBySpringCGLIB$$567d5bbf.invoke(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC8.jar!/:1.0.0-RC8]
29/10/2020 14:30:32	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691) ~[spring-aop-5.2.7.RELEASE.jar!/:5.2.7.RELEASE]
29/10/2020 14:30:32	at it.gov.pagopa.rtd.transaction_filter.batch.step.writer.PGPFlatFileItemWriter$$EnhancerBySpringCGLIB$$487b3e29.close(<generated>) ~[rtd-ms-transaction-filter-api-batch-1.0.0-RC8.jar!/:1.0.0-RC8]
29/10/2020 14:30:32	at org.springframework.batch.item.support.CompositeItemStream.close(CompositeItemStream.java:89) ~[spring-batch-infrastructure-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
29/10/2020 14:30:32	at org.springframework.batch.core.step.tasklet.TaskletStep.close(TaskletStep.java:306) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
29/10/2020 14:30:32	at org.springframework.batch.core.step.AbstractStep.execute(AbstractStep.java:286) ~[spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
29/10/2020 14:30:32	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:138) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
29/10/2020 14:30:32	at org.springframework.batch.core.partition.support.TaskExecutorPartitionHandler$1.call(TaskExecutorPartitionHandler.java:135) [spring-batch-core-4.2.4.RELEASE.jar!/:4.2.4.RELEASE]
29/10/2020 14:30:32	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_272]
29/10/2020 14:30:32	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_272]
29/10/2020 14:30:32	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_272]
29/10/2020 14:30:32	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
`

Il contenuto del file PGP, che riportiamo di seguito, è stato recuperato dal file [PDF RTD Acquirer interface versione 3](https://github.com/pagopa/rtd-ms-transaction-filter/blob/master/ops_resources/RTD_Acquirer_Interface_V3.pdf)

```
$ cat /BATCH/keys/pgp/pgp-public-sia.key
-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)
mQENBF+IZlwBCADQ4KTeUItBNzQScZMdJEP7GLmqvU0GCN7rrWG6qdhK7OvzQt/q
b2IrntqvilcIGiI59GfgsgyM0Rlpr5mkvPOv7no1KY5xW7r0c0ylBhKtX+xeFVbL
Ozu3YhqjSycinunTH8zbISSTIEe6p/+SzCyV231XwP0yjHvUskCe1dnDM+ceJxQc
jQ46sBQ4vXJtA3TkaTwyBMrCft0TW84mecdDtTw2b4zt0FcQtnpG0B8ZanFO+cqH
d9Z6qLhTcHQzMC8lSKIjKagPrWLJPfGuHzRh0YDIXSJp2aIqirfuHVDctN1dTqcV
JhP39qf6WOkJULEV8jFxWRR2QPkLzAw5gcQ/ABEBAAG0HnJ0ZGJjaHByMDEgPHJ0
ZGJjaHByMDFAc2lhLmV1PokBOQQTAQIAIwUCX4hmXAIbAwcLCQgHAwIBBhUIAgkK
CwQWAgMBAh4BAheAAAoJEFpOgVpChNKWddIIAJfx2Oh5zym2PLk8M40DGvcaVvyD
ZLsatwCCXknmD9xxOk7fg3084nSvYfdXS8+UXFZvO4FZolVzPMpZC/ODlDWOF4MC
4F7wMSGaia5Wf6Tp+KOGInDzaWzBlu9K5YspHG/ee5h0ioMBTcwq1Q0cK1Bbn35j
t8uBX1iD47Ea/F0F3A1ME5OkT+JC8t3RYN4DuTwEnhUL6TeVoVKziOWrvO1HyQKD
4BCeB/aw1lihbl8e3CLc0QNQqrH4CmiJDxjDv/Ozf9IdRqIXg34rtpdrgZnzC8Uo
ubyzq8dwkb1ohERfKpcxBSPhEhn2bVER5zbleu5gv6JbyzbgIj6ugUr9V9G5AQ0E
X4hm3gEIALoyR2/IQfdSVvkiP+HfVHdv2Vp1z98C+BhfLPuQ2kknBUXZaYMr5lB/
NYycLs+QFbxHtkA50qOAGzY/gjLv/+YrI9J0Wu5xlkZ1HCNWlpNMQwKWt8nh1vYo
EslweSZVRhDeCgwHzDDwdo/Xa/xIzdAqiMyxoS8yJVCwN11iyvNOgbwQUXFHe0BR
AIlBKKwibQi8DNi+9NU2gzZyiLh6WsAQQLVoIF3cS9sjhWcI+OB0NsffJ+oqkIb2
/wgpDwtUHclcTKGcB5HfueXCYnaBs+O/TO4W5w42Upg52s5tm9Mvaz8xbZW2ipi4
lyjeaPwm39aV/qTqkhwwlk3YpQH4BCUAEQEAAYkCPgQYAQIACQUCX4hm3gIbAgEp
CRBaToFaQoTSlsBdIAQZAQIABgUCX4hm3gAKCRAe9FqPx6cAANZAB/0eU9DXf6+s
Q6FeanXhDjzC1BP2qLtrED1hmIj8lrbAtk4AGyeTDhI5f1XiOuEqy9ATR9LOu4ap
97/3rItsX6J49gJeTCUYhBAEcJtRXHoU44PnyxYj1xn/kQqSd6iq/xtUDqSJrpxa
q42x/lSUmBhNZTa1JFPNWE4aedph9eiWIN/gT8/9m0cA/ZXfZuOKbq8EeTTJiSsd
Jq5blTitdbclREc781L2gCR2KHbunLXNSFYBAco/Pn6DR8PPmvKlPsKDVMHLO3u2
h/nrMmUMZ8t9u4TxMsX/V6DWdPVnmv8YWOFQdQGGMOIpJfEArp4j9+yPq7w9yMBD
uZcQyI6V91aQz8IH/RoYJOeVbMXbjRwtwcFIJlECH7LuGmVatq9x1ApqFnevxFb8
bZHltBgiPlChVrK4yttePP3/mv6ZzWSMhvDO9vVZuTZS1X9uAkk9rSBUnAFg0uj5
jF2sNw5x4UcP3qWlffY0DH5XEJhl0XfcAs/oIGIkJaK6PkioephcX5QlprKzUZBO
W0/XNa4R2IPVUdqIUdoBQd+7WzMoqfH6/30L+zw3mXVmaxgh0YLCdDYZapkeZ/Fn
nHTvJst7UUr0y/JwRCHL7Jc7R2lppkcRkhMoltbNF4JwkttGog4wDDbdBDS3wrgr
wRHXmjkRkZFGinR9pwteFVmh+jVgZu4Lx5GBbQc=
=fKwP
-----END PGP PUBLIC KEY BLOCK-----
```
Per comodità ne indichiamo di seguito anche il checksum MD5:

```
$ md5sum /BATCH/keys/pgp/pgp-public-sia.key
f0293f2a0f386e6d981e5944e6ad424f  /BATCH/keys/pgp/pgp-public-sia.key
```

Il riferimento alla chiave PGP viene fornito tramite variabile di ambiente, correttamente settata:

```
$ env | grep -i ACQ_BATCH_INPUT_PUBLIC_KEYPATH
ACQ_BATCH_INPUT_PUBLIC_KEYPATH=/BATCH/keys/pgp/pgp-public-sia.key
```

e riportata nel file di configurazione di esempio:

```
$ grep -i ACQ_BATCH_INPUT_PUBLIC_KEYPATH /BATCH/conf/application.yml
      publicKeyPath: file:${ACQ_BATCH_INPUT_PUBLIC_KEYPATH:}
```

Potreste aiutarci a risolvere l'errore?
Grazie,
Alessio

**Comment by t005627** [comment]
Ciao,
fornisco la mia esperienza, che può essere presa da spunto almeno per fare una prova, non come supporto ufficiale.

In ambiente SIT ho avuto il medesimo problema con la stessa eccezione rilanciata, risolto inserendo una riga vuota nel file della chiave dopo la riga "Version......."
Ossia:

-----BEGIN PGP PUBLIC KEY BLOCK-----
Version: GnuPG v2.0.22 (GNU/Linux)

mQENBF+IZlwBCADQ4KTeUItBNzQScZMdJEP7GLmqvU0GCN7rrWG6qdhK7OvzQt/q
...
...


Segnalo che copiando la chiave dal pdf la riga è assente, copiandola dal docx invece è presente.
Se potete fate almeno una prova in questo modo.

**Comment by alessio-cialini-sia** [comment]
Si, è possibile che nella copia del contenuto informativo si perda la formattazione corretta.

**Comment by alessio-cialini-sia** [comment]
La chiave pgp per uat è stata inclusa in ops_resources, per ulteriore convenienza
