### ISSUE TITLE
Informazioni su cifratura PGP

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#46]
Ciao,
vorrei chiedere alcune informazioni sulla cifratura PGP.

1)
La nomenclatura indicata sul documento "RTD_Acquirer_Interface_V3" è la seguente : 
[servizio].[ABI].[tipofile].[data].[ora].[nnn].csv

Inviando un file cifrato con pgp, dobbiamo aggiungere l'estensione .pgp, ossia utilizzare la seguente nomenclatura?
[servizio].[ABI].[tipofile].[data].[ora].[nnn].csv**.pgp**
oppure lasciare l'estensione .csv ?

2)
Abbiamo prodotto un file ed inviato al server sftp definito in "RTD_Acquirer_Interface_V3" per l'ambiente UAT.
I riferimenti per il supporto  indicati nel documento ci hanno segnalato che il file è stato correttamente ricevuto su sftp di destinazione, ma non possono verificare la cifratura.
Chi può validare che abbiamo applicato la corretta cifratura al file ?

Grazie.

**Comment by alessio-cialini-sia** [comment]
1) Il processo del batch aggiungerà in automatico l'estensione .pgp, quindi [servizio].[ABI].[tipofile].[data].[ora].[nnn].csv diventerà [servizio].[ABI].[tipofile].[data].[ora].[nnn].csv.pgp.

2) Per la verifica dovreste girare l'identificativo del file da controllare.

**Comment by t005627** [comment]
Ciao,
abbiamo inviato oggi il file con la seguente nomenclatura: CSTAR.12940.TRNLOG.20201030.171749.001.csv.pgp
Potreste confermarci la corretta ricezione ed, in secondo luogo, la corretta cifratura?

Grazie.

**Comment by alessio-cialini-sia** [comment]
File ricevuto, la cifratura è corretta.

**Comment by t005627** [comment]
Bene.
Approfitto per chiedere altre informazioni sulla stessa tematica.
1) Per l'ambiente di produzione come verrà fornita la chiave PGP da utilizzare?
2) Per il download del flusso HPAN, se non sbaglio in ambiente di test il file viene scaricato in chiaro.
Come si procederà in ambiente di produzione?

Grazie.

**Comment by riccardo-dellanna-sia** [comment]
Ciao,

1. la chaive PGP da utilizzare per l'ambiente di PROD è disponibile all'appendice 1 del documento RTD Acquirer Interface disponibile al seguente link: [https://github.com/pagopa/rtd-ms-transaction-filter/blob/master/ops_resources/RTD_Acquirer_Interface_V3.pdf]

2. In ambiente di PROD viene mantenuta la stessa struttura utilizzata in UAT ovvero viene scaricato un file di hpan in "chiaro" (un semplice file csv)

Grazie
