### ISSUE TITLE
Transazioni su carte privative

### ISSUE THREAD

**Issue by gimillan** [pagopa/rtd-ms-transaction-filter#47]
buongiorno,
le carte privative emesse da GDO o altri soggetti, possono essere trasmesse a PagoPA ? 
E in caso positivo, chi può trasmettere tecnicamente il file con le transazioni effettuate da carte privative ? 
Deve per forza essere l'acquirer, anche nel caso in cui le transazioni delle carte privative non siano gestite dall'acquirer ?

Inoltre le carte privative, si possono registrare solo tramite l'APP IO ? 
Grazie

**Comment by DenisaBraho** [comment]
Ciao,

le carte privative della GDO sono incluse nel perimetro. 
Per la loro natura di carte privative PagoPa sta valutando soluzioni custom con i principali player di mercato per trovare la migliore in termini di fattibilità per gli attori della filiera. Nelle prossime settimane, ci sarà un aggiornamento delle specifiche di interfaccia che descrivano anche questa soluzione

Saluti
