### ISSUE TITLE
From SIT to production

### ISSUE THREAD

**Issue by t005491** [pagopa/rtd-ms-transaction-filter#48]
Hello. In order to move from SIT environment to production, we would want to be sure about the procedure related to client certificate setup.  We have to perform the same procedure used for SIT (in the case, we have already sent by email our client certificate, created for prod environment, with the chain used to guarantee it), or we have to send you a CSR in order to get the certificate signed by you?
Finally, about the Ocp-Apim-Subscription-Key for prod, as done for SIT, can we generate it by ourselves using the developer portal?
Best regards.

**Comment by alessio-cialini-sia** [comment]
You'll have to send a .csr file to the following to security@pagopa.it. For the subscription key you should be able to proceed using the developer portal: https://developer.cstar.pagopa.it/

**Comment by t005491** [comment]
Hello. I reopen/reuse this thread just in order to close the point with the last environment, UAT. As intermediate environment, which iter we have to follow (client-certificate signed with our CA, as in SIT, or send you a CSR to be signed by yourself, as in production)?
Best regards.
