### ISSUE TITLE
Richiesta informazioni - Errore

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#49]
Ciao,

L'applicazione traccia il seguente errore:

"Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step"

Nella tabella di dettaglio delle eccezioni viene riportato:

"Recovered PAN list exceeding a day"

Potete aiutarmi a capirne la causa?
In generale, dove trovo l'elenco degli errori gestiti e la relativa causa?

grazie.

Saluti,
Mauro

**Comment by alessio-cialini-sia** [comment]
Quale ambiente produce questo errore?

**Comment by mripari** [comment]
Produzione
usiamo la RC8 con Fix

**Comment by alessio-cialini-sia** [comment]
L'errore deriva dalla mancata generazione del file dei pan, in fase di verifica.

Temporaneamente potete procedere disabilitando in configurazione questa proprietà:

**- rest-client.hpan.list.dateValidation: ${ACQ_BATCH_HPAN_LIST_DATE_VALIDATION:true}**

**Comment by alessio-cialini-sia** [comment]
Il problema dovrebbe essere in risoluzione, verificate nel caso a validazione attiva che il batch non produca errori di validazione del contenuto scaricato.
