### ISSUE TITLE
Azure connection

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#52]
Hello,
I'm trying to connect with Azure for the hashedPans and Salt seervices, but I receive the error 403 Forbidden.
I'm tryng to access with both
https://bpd-dev.azure-api.net:${HPAN_SERVICE_PORT:443}}/rtd/payment-instrument-manager
and
https://bpd-dev.developer.azure-api.net:${HPAN_SERVICE_PORT:443}}/rtd/payment-instrument-manager

I'have requested and inserted the subscription key.
How can I do?

Thank you 
Marco

**Comment by DenisaBraho** [comment]
Hello Marco,
could you please indicate the Acquirer's name?
Thank You

**Comment by s77937** [comment]
Six Payment/Worldline

Kind regards,


Marco Maglione
Information Analyst Sr
equensWorldline SE
T +39 06 5470 533
E marco.maglione@equensworldline.com<mailto:marco.maglione@equensworldline.com>
Via Elio Chianesi 110/D
00128 Roma
Italy
equensworldline.com<https://www.equensworldline.com/>

[Description: Description: Description: Description: Description: cid:image002.png@01D69D91.8DFD6120]
[Description: Description: Description: Description: Description: cid:image009.jpg@01D69D91.8DFD6120]<equensworldline.com/newsletter> [Description: Description: Description: Description: Description: cid:image010.jpg@01D69D91.8DFD6120] <equensworldline.com/twitter>  [Description: Description: Description: Description: Description: cid:image011.jpg@01D69D91.8DFD6120] <equensworldline.com/linkedin>  [Description: Description: Description: Description: Description: cid:image012.jpg@01D69D91.8DFD6120] <equensworldline.com/blog>  [Description: Description: Description: Description: Description: cid:image013.jpg@01D69D91.8DFD6120] <equensworldline.com/youtube>

**Comment by s77937** [comment]
Six Payment/Worldline

**Comment by lucasomarugasia** [comment]
Buongiorno, non risultate essere nella lista dei soggetti accreditati per le attività di integrazione. Vi chiediamo la cortesia di inviare richiesta a account@pagopa.it.
