### ISSUE TITLE
verifica correttezza tracciato CSV e crittografia

### ISSUE THREAD

**Issue by antessio** [pagopa/rtd-ms-transaction-filter#53]
Come si può sapere se il CSV sottomesso sul server SFTP è stato processato correttamente?

Sarebbe utile, anche in UAT, avere la possibilità di effettuare una verifica sia sulla validità del csv e sulla crittografia. 

Grazie

**Comment by riccardo-dellanna-sia** [comment]
Per la pianificazione degli invii di file in fase di test e verifiche sulla correttezza formale del flusso transazioni e sull'elaborazione del file da parte di Centro Stella vi chiedo gentilmente di contattarci via mail all'indirizzo cons.dellannariccardo@sia.eu

Grazie
