### ISSUE TITLE
Impossibile scaricare lista dei PAN

### ISSUE THREAD

**Issue by saracarissoni** [pagopa/rtd-ms-transaction-filter#54]
Si richiede di verificare il motivo per cui il Batch Acquirer non riesce a scaricare il file con la lista dei pan,
l'errore che ottiene è il seguente:
"Encountered an error executing step transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job"
Riscontriamo problemi anche nel download del salt.

**Comment by DenisaBraho** [comment]
Ciao,
l'anomalia segnalata è stata risolta.
Saluti
