### ISSUE TITLE
Batch Acquirer appeso

### ISSUE THREAD

**Issue by mripari** [pagopa/rtd-ms-transaction-filter#56]
Ciao,

l'applicazione è partita alle 14:01 ed ha trovato un file da processare, ma poi non ha proseguito, ed è ferma da 50 minuti.
Non vediamo informazioni aggiuntive nella tabella degli eventi e nemmeno nella tabella delle eccezioni.

Per cortesia, potete fare una verifica?

grazie

**Comment by alessio-cialini-sia** [comment]
Buonasera,

I tempi sono sempre relativi alla dimensione dei file letti e processati, pertanto sotto dimensioni estremamente elevate è possibile che il processo rimanga appeso per diverso tempo.

Lato nostro ci è ovviamente impossibile effettuare verifiche su di un processo esterno, a meno di dare indicazioni più specifiche, quali tracce di log più parlanti.

Buon proseguimento,

Alessio Cialini

**Comment by mripari** [comment]
Purtroppo non ci sono ulteriori informazioni nei log: il processo "dichiara" di aver trovato un file da processare e poi non fa più nulla, e non logga nulla, in nessuna tabella (il livello di log è DEBUG)

**Comment by alessio-cialini-sia** [comment]
Ciao,

Provate ad abilitare la scrittura intermedia delle letture.

batchConfiguration.TransactionFilterBatch.transactionFilter.readers.listener.enableAfterReadLogging: ${ACQ_BATCH_TRX_AFTER_READ_LOGGING_ENABLED:true}

Buon proseguimento,

Alessio Cialini

**Comment by mmelega-icteam** [comment]
Come indicato abbiamo provveduto a portare a 4G la memoria dedicata al BA ed abilitare la scrittura intermedia delle letture, ma il problema si sta ripresentando anche oggi e nella logging event non compaiono righe di scrittura intermedia.

**Comment by mmelega-icteam** [comment]
Abbiamo recuperato i log sulla macchina di una delle esecuzioni incriminate:

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 systemd: Removed slice User Slice of root.

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: 16:01:01,155 |-ERROR in ch.qos.logback.classic.db.DBAppender[SIMPLE_DB] - problem appending event java.sql.SQLException: ORA-01461: can bind a LONG value only for insert into a LONG column

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at java.sql.SQLException: ORA-01461: can bind a LONG value only for insert into a LONG column

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:450)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CTTIoer.processError(T4CTTIoer.java:399)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4C8Oall.processError(T4C8Oall.java:1059)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CTTIfun.receive(T4CTTIfun.java:522)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CTTIfun.doRPC(T4CTTIfun.java:257)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4C8Oall.doOALL(T4C8Oall.java:587)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:225)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CPreparedStatement.doOall8(T4CPreparedStatement.java:53)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.T4CPreparedStatement.executeForRows(T4CPreparedStatement.java:943)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.OracleStatement.doExecuteWithTimeout(OracleStatement.java:1150)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.OraclePreparedStatement.executeInternal(OraclePreparedStatement.java:4798)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.OraclePreparedStatement.executeUpdate(OraclePreparedStatement.java:4875)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at oracle.jdbc.driver.OraclePreparedStatementWrapper.executeUpdate(OraclePreparedStatementWrapper.java:1361)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.db.DBAppender.subAppend(DBAppender.java:104)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.db.DBAppender.subAppend(DBAppender.java:43)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.core.db.DBAppenderBase.append(DBAppenderBase.java:105)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.core.UnsynchronizedAppenderBase.doAppend(UnsynchronizedAppenderBase.java:84)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.core.spi.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:51)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.Logger.appendLoopOnAppenders(Logger.java:270)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.Logger.callAppenders(Logger.java:257)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.Logger.buildLoggingEventAndAppend(Logger.java:421)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.Logger.filterAndLog_0_Or3Plus(Logger.java:383)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at ch.qos.logback.classic.Logger.log(Logger.java:765)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.apache.commons.logging.LogAdapter$Slf4jLocationAwareLog.error(LogAdapter.java:426)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.handler.LoggingHandler.handleMessageInternal(LoggingHandler.java:187)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.handler.AbstractMessageHandler.handleMessage(AbstractMessageHandler.java:170)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.dispatcher.BroadcastingDispatcher.invokeHandler(BroadcastingDispatcher.java:224)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.dispatcher.BroadcastingDispatcher.dispatch(BroadcastingDispatcher.java:180)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.channel.AbstractSubscribableChannel.doSend(AbstractSubscribableChannel.java:73)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.channel.AbstractMessageChannel.send(AbstractMessageChannel.java:453)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:187)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:166)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.messaging.core.GenericMessagingTemplate.doSend(GenericMessagingTemplate.java:47)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.messaging.core.AbstractMessageSendingTemplate.send(AbstractMessageSendingTemplate.java:109)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.integration.channel.MessagePublishingErrorHandler.handleError(MessagePublishingErrorHandler.java:96)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:60)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.FutureTask.run(FutureTask.java:266)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

Dec 13 16:01:01 sbcashlesspeprd01-pp01-app0 batch-transaction-filter: at #011at java.lang.Thread.run(Thread.java:748)

Dec 13 16:03:25 sbcashlesspeprd01-pp01-app0 systemd: Configuration file /usr/lib/systemd/system/xagt.service is marked world-inaccessible. This has no effect as configuration data is accessible via APIs without restrictions. Proceeding anyway.

Dec 13 16:05:01 sbcashlesspeprd01-pp01-app0 systemd: Created slice User Slice of root.

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Il problema non è sul processo di acquiring, ma sull'appender a DB di logback, un errore simile è derivante presumibilmente da un uso non corretto della versione errata del driver per il database oracle.

Buon proseguimento,

Alessio Cialini

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

In parziale rettifica sembrerebbe che il problema sia nel fatto che su di un campo varchar2 sia arrivata una entry con più di 4000 caratteri, cosa che il sistema tenta di convertire come LONG, che però comunque nelle ultime versioni di Oracle dovrebbe essere deprecato.

Dovreste provare a verificare quale colonna sta producendo il problema, e provare a cambiarla a tipo CLOB.

Se il problema sull'appender non è di facile di soluzione, consiglio di rimuovere temporaneamente il logging su db, e procedere comunque all'esecuzione. Potrebbe trattarsi di un problema derivato da potenziali eccezioni, e vi sarebbe utile capire eventuali problemi sottostanti.

Buon proseguimento,

Alessio Cialini

**Comment by mmelega-icteam** [comment]
Buongiorno,
avete delle indicazioni su quali sono i campi sui quali eventualmente
intervenire. Dai log non si ha nessun indizio, dovremmo modificare i
livelli di logging in qualche modo? Se si come?

Grazie
MM

On Mon, Dec 14, 2020 at 11:13 AM alessio-cialini-sia <
notifications@github.com> wrote:

> Buongiorno,
>
> In parziale rettifica sembrerebbe che il problema sia nel fatto che su di
> un campo varchar2 sia arrivata una entry con più di 4000 caratteri, cosa
> che il sistema tenta di convertire come LONG, che però comunque nelle
> ultime versioni di Oracle dovrebbe essere deprecato.
>
> Dovreste provare a verificare quale colonna sta producendo il problema, e
> provare a cambiarla a tipo CLOB.
>
> Se il problema sull'appender non è di facile di soluzione, consiglio di
> rimuovere temporaneamente il logging su db, e procedere comunque
> all'esecuzione. Potrebbe trattarsi di un problema derivato da potenziali
> eccezioni, e vi sarebbe utile capire eventuali problemi sottostanti.
>
> Buon proseguimento,
>
> Alessio Cialini
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F56%23issuecomment-744335062&e=5793e774&h=cd9a6076&f=n&p=y>,
> or unsubscribe
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARR2G67ZRJ2AD5D3XVRKGGDSUXQNPANCNFSM4UWVDJMA&e=5793e774&h=a175c2f0&f=n&p=y>
> .[image: Web Bug from
> https://github.com/notifications/beacon/ARR2G6544S2UW55VON3OOOTSUXQNPA5CNFSM4UWVDJMKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFRO2NVQ.gif]
>


-- 

*Massimiliano Melega*
Senior Business Intelligence Engineer & Solution Architect
massimiliano.melega@icteam.it
+39 035 4232 287

[image: ICTeam Logo] <http://www.icteam.it>
* <http://www.icteam.it> *

*ICTeam S.p.A. • Via Azzano San Paolo, 139 Grassobbio BG 24050 Italy *P.IVA
02691680165 – Bergamo - REA-BG-314847

-- 

* <https://www.italianchannelawards.it/votazione.php>*



*Il contenuto di 
questo messaggio e-mail e di ogni eventuale allegato è strettamente 
confidenziale e indirizzato esclusivamente al destinatario indicato. Tutte 
le informazioni contenute sono soggette ad obbligo di riservatezza ai sensi 
del Regolamento UE 2016/679 GDPR e del D.Lgs 196/2003 e sm. Il trattamento 
non autorizzato del contenuto trasmesso e/o allegato dal mittente è 
vietato. In caso di erronea ricezione il destinatario è pregato di 
contattare immediatamente il mittente e cancellare al più presto il 
messaggio. Grazie.    *

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Sembrerebbe che l'unico elemento nello script a varchar 4000 sia formatted_message della tabella logging_event, provate a considerare quel valore.

Buon proseguimento,

Alessio Cialini

**Comment by DenisaBraho** [comment]
Ciao, procediamo con la chiusura della issue. Qualora dovessero esserci tuttavie delle problematiche, vi chiediamo di riaprire la issue in questione oppure procedere con l'apertura di una nuova.
Saluti
