### ISSUE TITLE
java.lang.OutOfMemoryError durante il download degli hpan

### ISSUE THREAD

**Issue by mmelega-icteam** [pagopa/rtd-ms-transaction-filter#57]
Durante l'esecuzione di un job si è verificato l'errore riportato. In allegato gli step.
[batch_step_log_2620.xlsx](https://github.com/pagopa/rtd-ms-transaction-filter/files/5679650/batch_step_log_2620.xlsx)

**Comment by daniloMessinaSia** [comment]
Buonasera,
quanta ram è stata dedicata alle JVM?

**Comment by mmelega-icteam** [comment]
Nello script di avvio del servizio Linux non sono indicati parametri per la
Ram
Quindi direi quella di default e con la quale sono state fatte tutte le
attività di Uat e produzione nascosta

Grazie
MM

Il Ven 11 Dic 2020, 20:53 daniloMessinaSia <notifications@github.com> ha
scritto:

> Buonasera,
> quanta ram è stata dedicata alle JVM?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F57%23issuecomment-743395103&e=5793e774&h=bfc24369&f=n&p=y>,
> or unsubscribe
> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARR2G6YD2U7PZNUSAT6IY53SUJ2ERANCNFSM4UWWQ5SQ&e=5793e774&h=c0a4f7c9&f=n&p=y>
> .[image: Web Bug from
> https://github.com/notifications/beacon/ARR2G66HXRQTCT3WMIYIKF3SUJ2ERA5CNFSM4UWWQ5S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFRHU6HY.gif]
>

-- 

* <https://www.italianchannelawards.it/votazione.php>*



*Il contenuto di 
questo messaggio e-mail e di ogni eventuale allegato è strettamente 
confidenziale e indirizzato esclusivamente al destinatario indicato. Tutte 
le informazioni contenute sono soggette ad obbligo di riservatezza ai sensi 
del Regolamento UE 2016/679 GDPR e del D.Lgs 196/2003 e sm. Il trattamento 
non autorizzato del contenuto trasmesso e/o allegato dal mittente è 
vietato. In caso di erronea ricezione il destinatario è pregato di 
contattare immediatamente il mittente e cancellare al più presto il 
messaggio. Grazie.    *

**Comment by mmelega-icteam** [comment]
+ Malovini

Il Ven 11 Dic 2020, 21:55 Massimiliano Melega <massimiliano.melega@icteam.it>
ha scritto:

> Nello script di avvio del servizio Linux non sono indicati parametri per
> la Ram
> Quindi direi quella di default e con la quale sono state fatte tutte le
> attività di Uat e produzione nascosta
>
> Grazie
> MM
>
> Il Ven 11 Dic 2020, 20:53 daniloMessinaSia <notifications@github.com> ha
> scritto:
>
>> Buonasera,
>> quanta ram è stata dedicata alle JVM?
>>
>> —
>> You are receiving this because you authored the thread.
>> Reply to this email directly, view it on GitHub
>> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fpagopa%2Frtd-ms-transaction-filter%2Fissues%2F57%23issuecomment-743395103&e=5793e774&h=bfc24369&f=n&p=y>,
>> or unsubscribe
>> <https://urlsand.esvalabs.com/?u=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FARR2G6YD2U7PZNUSAT6IY53SUJ2ERANCNFSM4UWWQ5SQ&e=5793e774&h=c0a4f7c9&f=n&p=y>
>> .[image: Web Bug from
>> https://github.com/notifications/beacon/ARR2G66HXRQTCT3WMIYIKF3SUJ2ERA5CNFSM4UWWQ5S2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOFRHU6HY.gif]
>>
>

-- 

* <https://www.italianchannelawards.it/votazione.php>*



*Il contenuto di 
questo messaggio e-mail e di ogni eventuale allegato è strettamente 
confidenziale e indirizzato esclusivamente al destinatario indicato. Tutte 
le informazioni contenute sono soggette ad obbligo di riservatezza ai sensi 
del Regolamento UE 2016/679 GDPR e del D.Lgs 196/2003 e sm. Il trattamento 
non autorizzato del contenuto trasmesso e/o allegato dal mittente è 
vietato. In caso di erronea ricezione il destinatario è pregato di 
contattare immediatamente il mittente e cancellare al più presto il 
messaggio. Grazie.    *

**Comment by daniloMessinaSia** [comment]
Buongiorno,
potreste provare ad aumentare la memoria utilizzata dal processo impostandola a 4GB (tramite la configurazione della JVM -Xmx4G).
Attualmente, il file degli hpan pesa circa 180mb

**Comment by DenisaBraho** [comment]
Ciao, procediamo con la chiusura della issue. Qualora dovessero esserci tuttavie delle problematiche, vi chiediamo di riaprire la issue in questione oppure procedere con l'apertura di una nuova.
Saluti
