### ISSUE TITLE
Exception hiding

### ISSUE THREAD

**Issue by zukrin** [pagopa/rtd-ms-transaction-filter#6]
In https://github.com/pagopa/rtd-ms-transaction-filter/blob/3f431995b82dde55fcd74a2e11d0cea02865c2f9/api/batch/src/main/java/it/gov/pagopa/rtd/transaction_filter/batch/step/reader/PGPFlatFileItemReader.java#L62 the Exception remains hidden. This should be avoided.

**Comment by alessio-cialini-sia** [comment]
Issue solved on #9
