### ISSUE TITLE
Richiesta informazioni per invocazione stand-alone della richiesta salt

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#60]
Buongiorno,
per necessità legate alla normativa PCI abbiamo delle difficoltà a sottoporre al batch la lista delle transazioni con i pan in chiaro.
Per questo motivo avremmo la necessità di ottenere in modo indipendente il salt per poi eseguire noi le operazioni di hashing nel nostro ambiente "protetto".

Volevamo dunque sapere se vi fosse la possibilità di configurare il batch per :

1. richiedere solamente il salt o solamente la lista degli hpan
2. mettere a disposizione il salt richiesto in un'opportuna directory

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Allo stato attuale disabilitando la richiesta del salt non sarebbe possibile ottenere l'hash corretto, non è previsto che sia posto come informazione all'interno di una directory. 

Il processo al momento è funzionale sulla base della gestione delle transazioni con pan in chiaro.

Buon proseguimento,

Alessio Cialini
