### ISSUE TITLE
Cancellazione file temporaneo HPAN

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#61]
Ciao,
vorrei chiedere una verifica sul comportamento del batch a riguardo del download del file con gli hashed pans.
Sulla nostra installazione, mi sembra venga scaricato in /var/tmp/
Al termine dell'esecuzione non mi sembra venga cancellato.
C'è la possibilità di configurare il batch per effettuarne la cancellazione?
Abbiamo impostato la proprietà manageHpanOnSuccess a "DELETE" ma questa non mi pare sortire effetto.

Grazie.

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

La cancellazione è valida solo per i file che effettivamente sono stati letti e processati dal processo batch, assicuratevi che i file che state vedendo siano effettivamente processati dal batch, le configurazioni della cartella di download, e quella della lista hpan devono coincidere.

Buon proseguimento,

Alessio Cialini
