### ISSUE TITLE
CharSet file di input

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#62]
Ciao,
avremmo bisogno di un chiarimento riguardo il charset gestito dal batch, in modo che legga senza problemi i file di input.
Inoltre se l' "a capo" dovrà essere LF oppure CR+LF o se vanno bene entrambi. 
Cortesemente potreste darci le specifiche a riguardo?

Grazie

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

Potete prendere esempio dai file presenti sotto la cartella ops_resources/example_files, per le questioni di charset e formattazione.
