### ISSUE TITLE
Splunk monitoring

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#65]
Ciao,
vorremmo agganciare il batch al monitoraggio Splunk. Quali sono le tabelle da monitorare, in cui sono registrati gli eventi che dovrebbero scatenare degli alert su Splunk durante l'esecuzione del batch (ad es. mancato colloquio con il server sftp, mancata ricezione hashedpans dal WS PagoPa, ecc.)? A vostro avviso quali eventi andrebbero monitorati?

Grazie

**Comment by DenisaBraho** [comment]
Ciao, 
nelle tabelle dello spring batch ci sono informazioni sommarie sullo stato di esecuzione. Per monitoring di dettaglio dovrà essere utilizzato un logger verso DB/Coda su cui fare monitoraggio.

**Comment by s77937** [comment]
Ciao,
cosa intendi per logger verso DB/Coda?

**Comment by alessio-cialini-sia** [comment]
Le tabelle utilizzate dallo sping batch non prevedono informazioni di dettaglio, ma solo informazioni in merito allo stato sommario delle esecuzioni.

Per ottenere un comportamento di monitoraggio come quello desiderato dovreste applicare una configurazione con un appender logback verso database o coda Kafka, oppure dovreste gestire l'invio dei log su stack ELK.

Le informazioni inerenti alle tabelle di spring, ed eventualmente quelle utilizzate da logback, sono descritte nel README, e gli script e file di configurazione d'esempio sono presenti in ops_resources

**Comment by s77937** [comment]
Riprendendo quanto riportato nel README: 
_As an example, a simple way to route all the produced logs from the console to a specific file, can be easly done by inserting a simple configuration within the application.yaml file, using the following configuration properties

logging.file="<path_to_log>/application.log" logging.pattern= logging.console=_

ho provato a configurare il file application.yml nel seguente modo:
logging:
  level:
    it.gov.pagopa.rtd.transaction_filter: ${LOG_LEVEL_RTD_TRANSACTION_FILTER:àNFO}
  file:"application.log" 
  pattern: 
  console:

ma il batch mi dà una eccezione nella lettura di questo file

**Comment by s77937** [comment]
configurandolo così funziona:
logging:
level:
it.gov.pagopa.rtd.transaction_filter: ${LOG_LEVEL_RTD_TRANSACTION_FILTER:àNFO}
file: "application.log"

**Comment by s77937** [comment]
ho configurato i 2 file nel seguente modo, ma pur facendo il batch il giro completo non scrive nulla nella tabella logging_event. Scrive invece regolarmente gli step nella tabella batch_jpb_execution.
Cosa stiamo sbagliando?

logback-spring.xml:
<configuration debug="true" scan="true" scanPeriod="30 seconds">

    <property resource="file:batch-transaction-file/property/application.yml" />

    <springProperty name="spring.datasource.driverClassName" source="org.hsqldb.jdbc.JDBCDriver"/>
    <springProperty name="spring.datasource.url" source="jdbc:hsqldb:hsql://localhost/cashbackdb"/>
    <springProperty name="spring.datasource.username" source="SA"/>
    <springProperty name="spring.datasource.password" source=""/>


    <appender name="SIMPLE_DB" class="ch.qos.logback.classic.db.DBAppender">
        <connectionSource class="ch.qos.logback.core.db.DriverManagerConnectionSource">
            <driverClass>${spring.datasource.driverClassName}</driverClass>
            <url>${spring.datasource.url}</url>
            <user>${spring.datasource.username}</user>
            <password>${spring.datasource.password}</password>
        </connectionSource>
    </appender>

    <root level="INFO">
        <appender-ref ref="SIMPLE_DB"/>
    </root>

</configuration>

application.yml:
.....
logging:
  level:
    it.gov.pagopa.rtd.transaction_filter: ${LOG_LEVEL_RTD_TRANSACTION_FILTER:INFO}
  config:
    classpath: "C:/Users/a481167/java/cashback/batch-transaction-file/property/logback-spring.xml"
.....

**Comment by alessio-cialini-sia** [comment]
Il path deve essere indicato semplicemente sotto config. Come verifica, con questo appender non è previsto un stdout dopo lo startup.
