### ISSUE TITLE
Hashing pan del file di input

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#66]
Buongiorno,
dove posso vedere il file di input dopo che il batch ha fatto l'hashing dei pan in chiaro?
Ho settato nel seguente modo queste properties del transactionFilter:
applyHashing: ${ACQ_BATCH_TRX_LIST_APPLY_HASHING:true} --> serve per fare l'hashing dei pan in chiaro presenti nel file di input usando la chiave del WS salt?
applyEncrypt: ${ACQ_BATCH_TRX_LIST_APPLY_ENCRYPT:true} --> a cosa serve??
saveHashing: ${ACQ_BATCH_TRX_LIST_HASHING_SAVE:true} --> serve a salvare il file di input dopo che il batch ha fatto l'hashing dei pan? Dove viene salvato?

**Comment by s77937** [comment]
Inoltre ho settato le seguenti properties:
deleteProcessedFiles: ${ACQ_BATCH_DELETE_LOCAL_FILE:false}
deleteOutputFiles: ${ACQ_BATCH_DELETE_OUTPUT_FILE:ERROR}
manageHpanOnSuccess: ${ACH_BATCH_HPAN_ON_SUCCESS:ARCHIVE}

**Comment by s77937** [comment]
Riguardo invece il panList ricevuto da WS, il flusso arriva cifrato, quindi devo mettere a true la properties applyDecript? Ed i pan arrivano già in hashing, per cui va bene mettere la properties applyhashing a false?
panList:
     .....
      applyDecrypt: ${ACQ_BATCH_PAN_LIST_APPLY_DECRYPT:false}
      applyHashing: ${ACQ_BATCH_PAN_LIST_APPLY_HASHING:false}

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

La spiegazione inerente alle proprietà di configurazione è ottenibile dall'appendice del README, in breve:

- la saveHashing non è più una configurazione applicabile a partire dalla RC9
- la applyEncrypt DEVE rimanere a true, in quanto i file di output devono essere criptati in pgp
- la applyHashing DEVE rimanere a true, in quanto indica l'applicazione dell'hashing ai PAN ottenuti dal file delle transazioni

Per il secondo punto, con la configurazione indicata il comportamento sarà che i file processati non saranno cancellati, i file di output verranno rimossi in caso d'errore, ed i file degli hpan saranno sempre spostati nelle cartelle d'archivio alla fine del processo,

Per la terza domanda lasciare a false entrambe le proprietà.
