### ISSUE TITLE
Naming convention

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#67]
Buongiorno,
è possibile inviare il file con una naming convention diversa da quella standard?

Ad esempio del tipo SPSDWH.CSTAR.TRXLOG.P_ABI_20210104061500_1_SPSDWHTRXFILEIT.csv.pgp, invece di CSTAR.ABI.TRNLOG.20201216.130000.001.CSV.pgp
 con l'ABI nostro ovviamente

**Comment by alessio-cialini-sia** [comment]
Sarebbe preferibile mantenere la naming convention regolare.

**Comment by s77937** [comment]
Abbiamo qualche problema a mantenere la naming convention regolare. Come si potrebbe aggirare questo vincolo?

**Comment by riccardo-dellanna-sia** [comment]
Come specificato dal collega Alessio, la naming convention prevista, attualmente utilizzata da tutti i soggetti terzi coinvolti sul progetto, andrebbe mantenuta come prevista dalle specifiche.
Potreste gentilmente indicarci quali sono le difficoltà che incontrate nel mantenere la naming convention prevista? Nel caso in cui sia preferibile, restiamo a disposizione per effettuare un eventuale meeting

**Comment by s77937** [comment]
Abbiamo appena terminato una riunione con i sistemisti e dovremmo aver trovato una soluzione per  inviare i file con la naming convention prevista. Facciamo delle prove e in caso occorra vi ricontattiamo.
Intanto chiudo la issue.
