### ISSUE TITLE
Chiarimenti vari

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#69]
Buongiorno,
avremmo bisogno di alcuni ulteriori chiarimenti:
• Limitazioni di volume / dimensione del file Trx, se presenti? Presumendo che non raggiungeremo presto alcuna limitazione (100k Trx = dimensione del file 15MB)
• Intervallo BIN 6 vs 8 cifre: sono sufficienti 6 cifre come impostazione predefinita corrente?
• Formato data e ora ISO8601 aaaa-MM-ggTHH: mm: ss.SSSXXXXX - possiamo assumere che XXXX siano segnaposto opzionali?
• Gestione per giorni festivi / festivi - eventuali consigli / regole specifici da prendere in considerazione?
Punto aggiuntivo:
• Utilizzo del PAN per i test: possiamo usare PAN "falsi" e PagoPa fornirà un hash corrispondente per simulare una carta registrata? O PagoPa fornirà PAN di prova che possiamo inserire nel file di importazione?

**Comment by alessio-cialini-sia** [comment]
- Non sono previsti limiti di dimensioni
- Consigliato applicare bin a 8 caratteri
- Nessun elemento del formato data è opzionale, XXXXX indica il timezone (esempio: +00:00)
- Nessuna considerazione particolare per date festive, lato processo batch

**Comment by s77937** [comment]
possiamo usare PAN falsi in test? O ci fornite voi dei pan per gli UAT?

**Comment by DenisaBraho** [comment]
Ciao, 
confermiamo che si possono utilizzare PAN fittizi. Vi chiediamo di indicarceli via mail a: TeamCentroStella@sia.eu la lista PAN ed eventualmente l'associazione PAN e CF in modo da censire le carte e comunicarvi gli HashPANs. Per effettuare dei test in ambiente di test si ricorda che lato Acquirer serve l'autenticazione tramite certificato.
Saluti
