### ISSUE TITLE
Transaction status

### ISSUE THREAD

**Issue by s77937** [pagopa/rtd-ms-transaction-filter#71]
Can we  populate the file with all the  ‘complete’ transactions  irrespective of the fact the transaction has been already settled or still not ?
Or we have to populate the file with only settled transactions ?

**Comment by DenisaBraho** [comment]
Hi,
could you explain in detail the meaning of "complete" transactions? 
In the designed process, the Acquirers should send the transactions' data to BPD after **posting** the transactions.

**Comment by DenisaBraho** [comment]
If you have other doubts or need any further details regarding this issue, we kindly ask you to reopen this issue or open a new one. Thank you
