### ISSUE TITLE
Invio SFTP tramite procedura proprietaria

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#75]
Buongiorno,
stavamo valutando la possibilità di effettuare l'invio SFT tramite delle nostre procedure interne.
A tal proposito avremmo alcune domande in merito a questa possibilità.

1. Per disabilitare l'invio SFTP è sufficiente valorizzare la property batchConfiguration.TransactionFilterBatch.transactionSender.enabled a FALSE? 

2. Nel caso di SFTP disabilitato nel batch, cosa succede ai file di output con i risultati? Rimangono nella cartella definita dalla property batchConfiguration.TransactionFilterBatch.transactionFilter.outputDirectoryPath?

3. Anche se l'SFTP del batch è disabilitato, i file di output sono comunque già cifrati in pgp, pronti per essere inviati? (nel senso che l'operazione di cifratura è processo a sè stante, indipendente dall'invio?).

**Comment by alessio-cialini-sia** [comment]
Si, per disabilitare l'invio SFTP settare la proprietà indicata a false, in quel caso i file rimarranno nella cartella di output, la cifratura avviene indipendentemente dall'abilitazione dell'invio su SFTP

**Comment by vghetta** [comment]
Perfetto, grazie per le risposte
