### ISSUE TITLE
No file found.

### ISSUE THREAD

**Issue by dsstoyanov** [pagopa/rtd-ms-transaction-filter#77]
Hello, 

First thanks for the reply!

I have a little progress with the configuration.
I was able to solve the '**cannot be resolved to URL because it does not exist**' problem and now the program displays: 

![Problem1](https://user-images.githubusercontent.com/24291538/105704017-c8570f00-5f16-11eb-82dc-84ecc049262a.PNG)

I have set in transactions folder the file from ../ops_resources/example_files/trx-list-input.csv
but it obviously can't find it as it can't find file in hpan directory.

Kindly asking you to assist if you can tell us which files to put in the appropriate directories.

Regards,
Deyan.

_Originally posted by @dsstoyanov in https://github.com/pagopa/rtd-ms-transaction-filter/issues/76#issuecomment-766779969_

**Comment by alessio-cialini-sia** [comment]
Hello, in order to obtain the hpan file, you'll have to enable the recovery from a rest endpoint. You can check the configuration example that you can find inside the ops_resources directory.

Please read throught the Readme to understand how to apply the configuration.
