### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by psihoterapeft** [pagopa/rtd-ms-transaction-filter#78]
Greetings,

We are in a process of integrating the transaction filter and we need assistance.

1. Can you please clarify what is the difference between the two environments SIT and UAT?
Is UAT env only needed for SFTP transfer as stated in Appendix 2? In SIT (azure) how is the file deposited?

2. We have registered to the portal https://bpd-dev.developer.azure-api.net and made a subscription to the RTD api product as per instructions, the status is ACTIVE.

We tried to get the SALT from the portal, but we receive 403 forbidden -

![Forbidden](https://user-images.githubusercontent.com/4932645/105828850-4de8c680-5fcc-11eb-9236-b71289c99405.png)

How can we test the API from the portal?

3. We have created a self-signed certificate as per instructions in Appendix 6 -

"N.B : for tests in the SIT environment, the client certificate can be self-signed, and
must be provided to the API publisher in ".pfx” format, while for higher environments
it must be signed by the PagoPA internal CA, and it is not necessary to share it with
the API Publisher. Consequently, the file containing the CA's public key should only
be provided by the Acquirers in the SIT environment."

Since we are targeting the SIT env , where do we need to send the certificate to, in order to test the connection from the app?

Thank you in advance.

**Comment by alessio-cialini-sia** [comment]
You'll have to send the request to add the root + intermidiate CA certificates used in the self-signed process to TeamCentroStella@sia.eu.

To avoid any problems, please explicitly state which acquirer is requesting to have is certificate added alongside the request.

**Comment by psihoterapeft** [comment]
Greetings,

We still have issue with the certificate.
We have sent it to TeamCentroStella@sia.eu and they added it. We are able to connect to SIT env with POSTMAN to get the salt, 
but we are unable to connect from the transaction-filter app. 

We have imported the certificate in truststore.jks and keystore,jks but it says 403 forbidden.

![image_2021_02_04T13_08_38_741Z](https://user-images.githubusercontent.com/4932645/107205384-7a5a0500-6a06-11eb-9bfe-e5b6c595d868.png)

Can you please advise?
