### ISSUE TITLE
FA Platform - T&C acceptance API

### ISSUE THREAD

**Issue by ttisch** [pagopa/rtd-ms-transaction-filter#81]
According to the docs we should send a PUT request to `/fa/onboarding/merchant/{vatNumber}`. But in de UAT developer portal there is no specification of this endpoint.

Only endpoint with similar purpose I found is: PUT `https://test.cstar.pagopa.it/fa/enrollment/hb/customer/{fiscalCode}`

Is this the one we need to use for "onboarding" merchants (so that they participate in the BPD program)?

Thanks in advance!
BR Thomas

**Comment by alessio-cialini-sia** [comment]
This is not an issue related to this component, look for the component BPD Enrollment.
