### ISSUE TITLE
Outfile Informations

### ISSUE THREAD

**Issue by aStiller01** [pagopa/rtd-ms-transaction-filter#82]
Is the out file a type of log file for monitoring the transmitted data and if so - at what point in time can I expect the out file to be delivered?
If so, are there only those transactions in the Out file that are also processed further by CentroStella after the HashPan has been compared?

Thanks in advance!
BR Alex

**Comment by alessio-cialini-sia** [comment]
Hi,

The output file will be on your system, and to monitor the process you'll have the informations from your log, and within the tables used by the Spring Batch framework, already described in the Readme of this repository.

The output file contains only the transaction matchin the hpan with the ones obtained from CentroStella. Depending on your configuration you may have additional files regarding filtered/error records.

Please refer to the documentation for further reading this subject.

**Comment by aStiller01** [comment]
Thanks for your Info
