### ISSUE TITLE
Values PagoPA flow

### ISSUE THREAD

**Issue by dollmaker2828** [pagopa/rtd-ms-transaction-filter#84]
I have three questions:

- What is the value for "ABI" in the filename? As far as I know, ABI is for italian banks only. We are not from Italy.
- What is the value for "aquirer_code" in the 1st column of the file? Is this the same code as "ABI" in the filename?
- What is the value for "acquirer_id" in the 11th column of the file?

**Comment by DenisaBraho** [comment]
Hello, we will give you a feedback. Could you please indicate your Acquirer's name? Thanks.

**Comment by dollmaker2828** [comment]
hobex AG

**Comment by DenisaBraho** [comment]
Hello,
below our answers:
1. You could use as ABI code the string "HOBEX"
2. Yes, it corresponds to the abi code in the filename. This field coudl contain also the value "HOBEX"
3. this Field must contain a data (ex. a fixed value) that identifies uniquely the Acquirer ("hobex AG" in this case) , so it can be valued with any alphanumeric data (max length 255).

Regards

**Comment by dollmaker2828** [comment]
Thank you!
