### ISSUE TITLE
Register at Automatic Invoicing for cashback

### ISSUE THREAD

**Issue by aStiller01** [pagopa/rtd-ms-transaction-filter#85]
Greetings, 

To fully anderstand the process for the cashback, I would like to know if we have to register our merchants at the ```Fatturazione Automatica``` (automatic invoicing) if they want to use cashback?

**Comment by DenisaBraho** [comment]
Hello, no, it's not necessary. 
The FA paragraph is not related to Cashback program and shouldn't be considered.
Regards
