### ISSUE TITLE
Informazioni sul motivo di scarto delle transazioni

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#86]
Salve,
da qualche giorno abbiamo iniziato ad inviare giornalmente le transazioni a CentroStella ed abbiamo iniziato ad ottenere dei files filteredRecords contenenti le transazioni scartate.
Analizzando il contenuto di tali files non ci sembra contengano la motivazione per cui una tal transazione sia stata scartata.
Abbiamo controllato anche la sezione delle istruzioni dove viene spiegato come attivare il log su tabella, ma anche in questo caso non sembra siano disponibili le informazioni relative alle scelte compiute dal job in fase di filtraggio.
Cortesemente volevamo chiedere se è prevista la possibilità di avere informazioni dettagliate sullo scarto delle transazioni, o direttamente nei files degli scarti, oppure in un qualche apposito log

**Comment by alessio-cialini-sia** [comment]
Le transazioni presenti nel file con prefisso FilteredRecords sono tutte le transazioni per cui non è presente l'hpan nel file fornito da CentroStella
