### ISSUE TITLE
api auth error and empty output file

### ISSUE THREAD

**Issue by hobex-scharf** [pagopa/rtd-ms-transaction-filter#87]
all calls to the bpd api fail with 403 forbidden, even the calls i make 
from the dev portal (https://bpd-dev.developer.azure-api.net/api-details#api=payment-instrument-manager-api&operation=get-hashed-pans), could 
you please check! i generated an api key and filled the truststore and use 
self signed cert

2021-02-16 13:06:00.030 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] ---> 
GET https://bpd-dev.azure-api.net:443/rtd/payment-instrument-manager/hashed-pans HTTP/1.1
2021-02-16 13:06:00.032 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] Ocp-
Apim-Subscription-Key: e88307adc1d243ddb292c6b49f4785a8
2021-02-16 13:06:00.032 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] ---> 
END HTTP (0-byte body)
2021-02-16 13:06:00.329 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] <--- 
HTTP/1.1 403 Certificate not verified: 
B235BA6F9AADF6E823570EE4F81323E8143BBE18 (296ms)
2021-02-16 13:06:00.329 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] 
content-length: 0
2021-02-16 13:06:00.329 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] date: 
Tue, 16 Feb 2021 13:06:00 GMT
2021-02-16 13:06:00.329 DEBUG 11452 --- [ask-scheduler-1] 
i.g.p.r.t.connector.HpanRestConnector    : [HpanRestConnector#getList] <--- 
END HTTP (0-byte body)
2021-02-16 13:06:00.332 ERROR 11452 --- [ask-scheduler-1] 
o.s.batch.core.step.AbstractStep         : Encountered an error executing step 
transaction-filter-salt-hpan-list-recovery-step in job transaction-filter-job

feign.FeignException$Forbidden: status 403 reading 
HpanRestConnector#getList(String)

additionally, when i go with the example hpan file and example input file and 
disable hpan/salt recovery from the api, the job runs but output file is 0 
bytes:

2021-02-16 13:19:00.901  INFO 11732 --- [rTaskExecutor-2] 
.r.t.b.s.l.TransactionReaderStepListener : Processing for file: file:/opt/btf/
resources/transactions/trx-list-input.csv ended with status: COMPLETED
2021-02-16 13:19:00.904  INFO 11732 --- [rTaskExecutor-2] 
o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-worker-
step:partition0] executed in 263ms
2021-02-16 13:19:00.912  INFO 11732 --- [ask-scheduler-1] 
o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-master-
step] executed in 281ms
2021-02-16 13:19:00.932  INFO 11732 --- [ask-scheduler-1] 
o.s.batch.core.job.SimpleStepHandler     : Executing step: [transaction-
sender-master-step]
2021-02-16 13:19:00.942  INFO 11732 --- [ask-scheduler-1] 
o.s.batch.core.step.AbstractStep         : Step: [transaction-sender-master-
step] executed in 10ms
2021-02-16 13:19:00.962  INFO 11732 --- [ask-scheduler-1] 
o.s.batch.core.job.SimpleStepHandler     : Executing step: [transaction-
filter-file-management-step]
2021-02-16 13:19:00.977  INFO 11732 --- [ask-scheduler-1] 
i.g.p.r.t.b.s.t.FileManagementTasklet    : Removing processed file: file:/opt/
btf/resources/hpans/hpan.csv
2021-02-16 13:19:00.987  INFO 11732 --- [ask-scheduler-1] 
i.g.p.r.t.b.s.t.FileManagementTasklet    : Archiving processed file: file:/
opt/btf/resources/transactions/trx-list-input.csv
2021-02-16 13:19:01.006  INFO 11732 --- [ask-scheduler-1] 
o.s.batch.core.step.AbstractStep         : Step: [transaction-filter-file-
management-step] executed in 44ms
2021-02-16 13:19:01.022  INFO 11732 --- [ask-scheduler-1] 
o.s.b.c.l.support.SimpleJobLauncher      : Job: [FlowJob: [name=transaction-
filter-job]] completed with the following parameters: 
[{startDateTime=1613481540000}] and the following status: [COMPLETED] in 860ms
2021-02-16 13:19:01.024  INFO 11732 --- [ask-scheduler-1] 
i.g.p.r.t.b.TransactionFilterScheduler   : CsvTransactionReader scheduled job 
ended at Tue Feb 16 13:19:01 GMT 2021
2021-02-16 13:19:01.024  INFO 11732 --- [ask-scheduler-1] 
i.g.p.r.t.b.TransactionFilterScheduler   : Completed in: 1024 (ms)

**Comment by alessio-cialini-sia** [comment]
As described in the guidelines, provided in this repository:

- for the SIT enviroment you'll have to send the .cer of the CA used for generating a self-signed certificate, you can send this request to TeamCentroStella@sia.eu
- For UAT and PROD, you'll have to send a request to sign your certificate to security@pagopa.it

In order to access the endpoints a subscription key is required, please refer to the documentation provided within ops_resources for a general guideline on how to obtain a valid subscription key for every enviroment.

**Comment by hobex-scharf** [comment]
hi, as i said, the api key is not even working on your own website when i test it! so it cannot be a cert issue. anyway, i've sent the csr to the mail address specified, but please check why this api key is not working on your test website. i generated the api key there and it lets me select it via dropdown menu, but is getting 403 response.
https://bpd-dev.developer.azure-api.net/api-details#api=payment-instrument-manager-api&operation=get-hashed-pans
check the screenshot: https://postimg.cc/gX32ksFf

**Comment by alessio-cialini-sia** [comment]
Hi, until the a valid certification is used, you'll always receive a 403 error

**Comment by hobex-scharf** [comment]
hi, i'm testing on your dev portal website, like manually in my browser. how do you use certificates there? did you look at the screenshot? for testing with the jar application i'm still waiting for the cert to be signed.

**Comment by alessio-cialini-sia** [comment]
If you want to test the endpoints outside of the application, please use a client like Postman, and use your certificate and key.

In SIT you'll have to provide your self-signed certificate to TeamCentroStella@sia.eu, and wait the confirmation before testing.

For UAT and PROD, please send the request to sign your certificate to security@pagopa.it

**Comment by hobex-scharf** [comment]
hello, please validate my api on test.cstar.pagopa.it it's still status submitted!thank you.

**Comment by hobex-scharf** [comment]
hello, please auth my api I need to start testing
