### ISSUE TITLE
sftp access and prod certs

### ISSUE THREAD

**Issue by hobex-scharf** [pagopa/rtd-ms-transaction-filter#88]
please point me to a contact where i can obtain sftp access and production certs and production api keys.

**Comment by alessio-cialini-sia** [comment]
The informations regarding the contacts for the sftp access, the production certificate, and the production keys are described within the documentation provided at https://github.com/pagopa/rtd-ms-transaction-filter/blob/master/ops_resources/RTD_Acquirer_Interface_V4_eng_post_Release.pdf.

**Comment by hobex-scharf** [comment]
is that sistemisti_bigdata@sia.eu ? i only see it mentioned as a pgp key contacts, but not for sftp. do i just send them my public rsa id?

**Comment by alessio-cialini-sia** [comment]
Refer to the details within the paragraph Appendix 2 - File Transfer Mode

**Comment by hobex-scharf** [comment]
could you kindly provide the mail address of the contact, thank you. there is only a phone number and i need to transfer keys.

**Comment by alessio-cialini-sia** [comment]
Please use the following structure <name>.<surname>@sia.eu
