### ISSUE TITLE
File temporanei prodotti dal batch

### ISSUE THREAD

**Issue by vghetta** [pagopa/rtd-ms-transaction-filter#89]
Salve,
i nostri sistemisti ci hanno segnalato che il batch produce ad ogni elaborazione un file temporaneo denominato hpanDownloadFileXXXXXXXXXXXXXXXXXXX (con X carattere numerico) e una directory chiamata hpanTempFolderXXXXXXXXXXXXXXXXXXX (con X carattere numerico).
E' possibile configurare il batch affinchè questi file e directories vengano eliminati al termine dell'elaborazione?
Abbiamo alcune problematiche legate sia allo spazio disco utlizzato, sia a degli errori su altri job dovuti ai particolari permessi assegnati alle directories (drwx--S---)

cordiali saluti
Ghetta Valerio

**Comment by alessio-cialini-sia** [comment]
Il comportamento sarà verificato ed in caso rettificato con rilascio dedicato. Attualmente non è presente una configurazione dedicata.

Nel caso ci siano problemi legati allo spazio prevedere la cancellazione dei file temporanei.
