### ISSUE TITLE
File input per ambiente SIT e UAT

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#93]
Ciao,
i file presenti sul repository in /ops_resources/example_files/ sono aggiornati?
In particolare mi riferisco al file trx-list-input.csv
Ho provato ad utilizzarlo in ambiente SIT ma tutte le transazioni risultano filtrate con il file hpan attualmente scaricato dal servizio.
Potreste verificare ed in caso aggiornare i file di esempio da utilizzare?

Grazie.

**Comment by alessio-cialini-sia** [comment]
Ciao,

Il file di esempio serve unicamente ad avere un riferimento per il formato, non è direttamente collegato al contenuto presente in SIT o UAT.

Se necessario avere dalla lista recuperata dagli ambienti SIT e UAT un particolare pan, dovrà essere comunicata la richiesta di aggiunta dei dati da trattare

**Comment by t005627** [comment]
Ciao,
non abbiamo necessità di censire pan specifici.
Potreste fornirci due liste (una per ogni ambiente) di 10 pan abilitati a vostra scelta?

Grazie.

**Comment by edo621** [comment]
Ciao,
potreste cortesemente lasciare un indirizzo email per fornirvi la lista?

A disposizione
Grazie

**Comment by t005627** [comment]
Certo, potete inviare la lista a questo indirizzo: t005627@iccrea.bcc.it

Vi ringrazio.
