### ISSUE TITLE
Verifica comportamento Batch Acquirer per 2 transaction filter partition innestati, di cui uno in errore

### ISSUE THREAD

**Issue by federico-cattaneo** [pagopa/rtd-ms-transaction-filter#94]
Ciao,
in data 27/4 abbiamo riscontrato un comportamento probabilmente anomalo del BA:

sono stati elaborati, dallo stesso processo, i file:
CSTAR.08000.TRNLOG.20210427.110038.001.CSV
CSTAR.03111.TRNLOG.20210427.100043.001.CSV
![err_2704](https://user-images.githubusercontent.com/82512221/116877153-d99e6e80-ac1d-11eb-81ea-364f09308ea0.JPG)
![err_2704_dett](https://user-images.githubusercontent.com/82512221/116877787-b32d0300-ac1e-11eb-9bfe-9a3cf0e718fb.JPG)

Il file *08000* è stato gestito dal BA senza errori, mentre il file *03111* è terminato in FAILED dopo poche migliaia di righe.
Il problema riscontrato è:
_162997	0	org.springframework.transaction.CannotCreateTransactionException: Could not open JPA EntityManager for transaction; nested exception is org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
162997	1		at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:448)
162997	2		at org.springframework.transaction.support.AbstractPlatformTransactionManager.startTransaction(AbstractPlatformTransactionManager.java:400)
162997	3		at org.springframework.transaction.support.AbstractPlatformTransactionManager.getTransaction(AbstractPlatformTransactionManager.java:373)
162997	4		at sun.reflect.GeneratedMethodAccessor55.invoke(Unknown Source)
162997	5		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
162997	6		at java.lang.reflect.Method.invoke(Method.java:498)
162997	7		at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:344)
162997	8		at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:198)
162997	9		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
162997	10		at org.springframework.batch.core.configuration.annotation.SimpleBatchConfiguration$PassthruAdvice.invoke(SimpleBatchConfiguration.java:127)
162997	11		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
162997	12		at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:212)
162997	13		at com.sun.proxy.$Proxy87.getTransaction(Unknown Source)
162997	14		at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:137)
162997	15		at org.springframework.batch.core.step.tasklet.TaskletStep$2.doInChunkContext(TaskletStep.java:273)
162997	16		at org.springframework.batch.core.scope.context.StepContextRepeatCallback.doInIteration(StepContextRepeatCallback.java:82)
162997	17		at org.springframework.batch.repeat.support.TaskExecutorRepeatTemplate$ExecutingRunnable.run(TaskExecutorRepeatTemplate.java:262)
162997	18		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
162997	19		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
162997	20		at java.lang.Thread.run(Thread.java:748)
162997	21	Caused by: org.hibernate.exception.JDBCConnectionException: Unable to acquire JDBC Connection
162997	22		at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:48)
162997	23		at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:42)
162997	24		at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113)
162997	25		at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99)
162997	26		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:107)
162997	27		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getPhysicalConnection(LogicalConnectionManagedImpl.java:134)
162997	28		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.getConnectionForTransactionManagement(LogicalConnectionManagedImpl.java:259)
162997	29		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.begin(LogicalConnectionManagedImpl.java:267)
162997	30		at org.hibernate.resource.transaction.backend.jdbc.internal.JdbcResourceLocalTransactionCoordinatorImpl$TransactionDriverControlImpl.begin(JdbcResourceLocalTransactionCoordinatorImpl.java:246)
162997	31		at org.hibernate.engine.transaction.internal.TransactionImpl.begin(TransactionImpl.java:83)
162997	32		at org.springframework.orm.jpa.vendor.HibernateJpaDialect.beginTransaction(HibernateJpaDialect.java:184)
162997	33		at org.springframework.orm.jpa.JpaTransactionManager.doBegin(JpaTransactionManager.java:402)
162997	34		... 19 common frames omitted
162997	35	Caused by: java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 11429ms.
162997	36		at com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
162997	37		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
162997	38		at com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
162997	39		at com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:128)
162997	40		at com.zaxxer.hikari.HikariDataSource$$FastClassBySpringCGLIB$$eeb1ae86.invoke(<generated>)
162997	41		at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
162997	42		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:771)
162997	43		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
162997	44		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
162997	45		at org.springframework.aop.support.DelegatingIntroductionInterceptor.doProceed(DelegatingIntroductionInterceptor.java:136)
162997	46		at org.springframework.aop.support.DelegatingIntroductionInterceptor.invoke(DelegatingIntroductionInterceptor.java:124)
162997	47		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
162997	48		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
162997	49		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
162997	50		at com.zaxxer.hikari.HikariDataSource$$EnhancerBySpringCGLIB$$67a55876.getConnection(<generated>)
162997	51		at org.hibernate.engine.jdbc.connections.internal.DatasourceConnectionProviderImpl.getConnection(DatasourceConnectionProviderImpl.java:122)
162997	52		at org.hibernate.internal.NonContextualJdbcConnectionAccess.obtainConnection(NonContextualJdbcConnectionAccess.java:38)
162997	53		at org.hibernate.resource.jdbc.internal.LogicalConnectionManagedImpl.acquireConnectionIfNeeded(LogicalConnectionManagedImpl.java:104)
162997	54		... 26 common frames omitted_

che sembra essere stato risolto a fronte dell'intervento di allargamento della RAM eseguito in data 30/4.
A fronte di questo errore il transaction filter master-step è andato in ABANDONED, ma nonostante questo ha prodotto ed inviato i 2 .pgp, sebbene uno dei 2 (quello 03111) non fosse completo.

Potete approfondire il comportamento del batch in queste situazioni e darci un riscontro?

Grazie
Federico

**Comment by alessio-cialini-sia** [comment]
Il problema indicato deriva da un crash dovuto a sotto-dimensionamento del pool di connessioni a disposizione dell'applicativo, per ovviare si suggerisce di procedere alla modifica della configurazione indicata nel paragrafo relativo nel Readme.

Il file parziale viene gestito eventualmente dalla configurazione indicata **solo** se individuato al termine dell'elaborazione del master-step, ed all'interno del passaggio transaction-filter-file-management-step.

I tracciati di output (csv e pgp) sono cancellati **solo** se impostata correttamente la proprietà deleteOuputFiles ad ERROR (comportamento di default), e nella fase di lettura dello step è stato possibile leggere i file.

Qualsiasi processo esterno che influisca sul passaggio prima dell'avvenuta lettura del file di output può comportare che non possa essere gestito per tempo.

I file gestiti per cancellazione dal processo batch sono tracciati con i log INFO _Deleting output file: <nome:file>_. 

La gestione dei file di output anche parziali deriva dalla potenziale configurazione per cui il tracciato di output prodotto fino ad eventuale errore può essere eventualmente già impiegato, in quanto si tratta di tutti i record validi e correttamente elaborati, e che internamente al processo batch, a seconda delle configurazioni, possono essere gestiti per l'invio da parte del modulo SFTP.
