### ISSUE TITLE
Cancellazione file temporanei hpan a seguito del download

### ISSUE THREAD

**Issue by Cristian-NETSGROUP** [pagopa/rtd-ms-transaction-filter#95]
Ciao,
stiamo riscontrando alcune problematiche riguardo la gestione dei file temporanei generati a seguito del download dei flussi hpan.

Il flusso una volta scaricato viene depositato nel path definito in configurazione e una volta terminata l'elaborazione viene rimosso correttamente.

Questo non avviene però per i file temporanei generati a seguito del download.
Il continuo download di questi file genera problematiche legate alla gestione dello spazio dedicato ai file temporanei che si satura rapidamente.

Potete fornirci informazioni sulla possibilità di eliminare automaticamente questi file o eventualmente di come possiamo gestirli per non incorrere in problematiche di esecuzione dell'applicazione?

Di seguito un esempio della lista dei file:
596932472 May  4 08:02 hpanDownloadFile6523251068656630058
       28 May  4 08:02 hpanTempFolder7855410857573815851
596932472 May  4 08:04 hpanDownloadFile3506795325805098193
       28 May  4 08:04 hpanTempFolder422786241330363553
596932472 May  4 08:06 hpanDownloadFile4053056799898773544
       28 May  4 08:06 hpanTempFolder8732077209026388761
       28 May  4 08:08 hpanTempFolder8790524332942782979
596932472 May  4 08:08 hpanDownloadFile4287460565273184735
596932472 May  4 08:10 hpanDownloadFile7907525671296503711
       28 May  4 08:10 hpanTempFolder1844065255001038733
596932472 May  4 08:12 hpanDownloadFile4943178482989095247
       28 May  4 08:12 hpanTempFolder5469134915868409128
596932472 May  4 08:14 hpanDownloadFile4325068293454814561
       28 May  4 08:14 hpanTempFolder3788745940041314969
596932472 May  4 08:16 hpanDownloadFile5236315023442112705
       28 May  4 08:16 hpanTempFolder3733495504805478906
       28 May  4 08:18 hpanTempFolder7900889465063542907
596932472 May  4 08:18 hpanDownloadFile7716724098427369571
        0 May  4 08:19 hpanDownloadFile8256741883479232897
596932472 May  4 08:21 hpanDownloadFile8197027755388676882
       28 May  4 08:21 hpanTempFolder2820277438182432688
       28 May  4 08:23 hpanTempFolder1235362016872455494
596932472 May  4 08:23 hpanDownloadFile7399537369167736217
        0 May  4 08:25 hpanDownloadFile8342211232212293680
        0 May  4 08:27 hpanDownloadFile1574066813667531061
        0 May  4 08:29 hpanDownloadFile8544831286736663078
        0 May  4 08:31 hpanDownloadFile3018014067425447247
        0 May  4 08:33 hpanDownloadFile1637278938289647423
        0 May  4 08:35 hpanDownloadFile2583496130426613827
        0 May  4 08:37 hpanDownloadFile7790435265133304970
        0 May  4 08:39 hpanDownloadFile3468223147396706691
        0 May  4 08:41 hpanDownloadFile8036828253058543653
        0 May  4 08:43 hpanDownloadFile1396282269195461196
        0 May  4 08:45 hpanDownloadFile6112897556930819013
        0 May  4 08:47 hpanDownloadFile268141430421499869
        0 May  4 08:49 hpanDownloadFile8911230264839548082
...

**Comment by alessio-cialini-sia** [comment]
Buongiorno,

La gestione dei file temporanei è stata migliorata con il rilascio della versione 1.0.2.

La modifica gestisce i file temporanei prodotti nel corso dell'elaborazione, i file precedenti dovranno essere rimossi manualmente.
