### ISSUE TITLE
Invio transazioni 

### ISSUE THREAD

**Issue by mpolleschi-marketpay** [pagopa/rtd-ms-transaction-filter#96]
Buongiorno,
stiamo entrando in fase di sviluppo e abbiamo le seguenti domande:
 - quale ID dobbiamo usare, in quanto acquirer? possiamo usare il codice EBA, giusto? 
 - i nostri sistemi di reportistica non sono attivi durante il weekend, quindi esiste una situazione limite in cui una transazione effettuata sabato potrebbe arrivare lunedì sera o addirittura martedì. Si considera questo fuori SLA oppure accettabile? 
 - potete confermare che è possibile sviluppare l'equivalente del vostro tool open source in un altro linguaggio (.NET)? 
 - potreste inviarci il vostro AOC? 
 - laddove il file delle transazioni non fosse ricevuto da PagoPA o se ci fossero problemi di invio, é prevista la possibilità di re-invio del file? Quali sono le proceudre da seguire in questo caso?
Grazie in anticipo,
Market Pay

**Comment by edo621** [comment]
Buongiorno,

i punti sono stati ripresi nell'email inviata il 12/05/2021 alle 16:15.
Prego di fare riferimento a quel thread laddove le risposte non fossero esaustive.

A disposizione
