### ISSUE TITLE
Errore java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by t005627** [pagopa/rtd-ms-transaction-filter#97]
Ciao, nella elaborazione odierna abbiamo riscontrato un errore analogo a quello segnalato in questa issue:
https://github.com/pagopa/rtd-ms-transaction-filter/issues/57

I parametri di memoria attualmente utilizzati dal batch sono quelli che ci sono stati indicati (“-Xms4g -Xmx4g“).

Potreste aiutarci nell'analisi del problema?

Grazie.

[batch_pago_log.txt](https://github.com/pagopa/rtd-ms-transaction-filter/files/6502031/batch_pago_log.txt)

**Comment by alessio-cialini-sia** [comment]
Nel caso di saturazione della memoria in questo momento la soluzione è quella di aumentare la memoria a disposizione del processo java.
